### ISSUE TITLE
text on castbar under nameplate

### ISSUE THREAD

**Issue by Demognum** [Luxocracy/NeatPlates#109]
Text moved to leftside on castbar under nameplates (was on center!) 
How to fix it?

![Screenshot_89](https://user-images.githubusercontent.com/54355325/63423929-fed15600-c415-11e9-96e3-4ab150739f47.png)
![Screenshot_90](https://user-images.githubusercontent.com/54355325/63423930-fed15600-c415-11e9-9481-d3d12d5f96fe.png)

**Comment by Luxocracy** [comment]
This was an intentional change to prevent the text overlapping with the newly added option to display cast times on the castbar. 
I didn't really see this as an issue as I think this still looks fine. But if this is something that really bugs you I should be able to make it only shift over to the left if you are actually displaying the cast time.

**Comment by Demognum** [comment]
I just want to move it to center :) thanks.

**Comment by Demognum** [comment]
Thanks a lot!!!
