### ISSUE TITLE
ClassWidget

### ISSUE THREAD

**Issue by DogmaTX** [Luxocracy/NeatPlates#119]
Every time, after updating the addon, I have to replace the icons in "ClassWidget" to others. Can you add a setting to the addon to change "ClassWidget" icons?

> .PSD
> https://drive.google.com/drive/folders/0B4FKMnxEVW1iaHlsTmc1ZDdWbWc?usp=sharing

> .TGA
> https://drive.google.com/drive/folders/0B4FKMnxEVW1idTBJeHpaNGJhMG8?usp=sharing

> .TGA ver.2
> https://drive.google.com/drive/folders/0B4FKMnxEVW1iaVFPTzJWTERJSVU?usp=sharing

**Comment by Luxocracy** [comment]
What I can do and believe is the better solution is add an override folder. So I could make it so that if you place your textures in `Interface\NeatPlatesTextures\ClassWidget\` it will use those firsts, and if it can't find them it will revert to defaults.

This way you won't have to change them everytime there's an update.

**Comment by hollo6** [comment]
While you're at it, could you think of some solution for modified themes as well?
I have replaced eliteicon and shifted its position and it would be good if I didn't have to manually replace all the files and code with every update. :)

**Comment by Luxocracy** [comment]
Well, you could make a new theme out of it by renaming the folder and changing the _ThemeName_ variable and the name in the .toc file to something else.

I was working on making it so you could modify and store themes in-game by basically having an in-game text editor. But I didn't really like that direction I was heading with that, because if you know how to do that you could probably as easily create your own theme as mentioned above.

**Comment by hollo6** [comment]
The reason I didn't want to do something like this is that you sometimes post updates/modifications to themes and they are almost always useful so I want them and merge with mine. And my goal would be to avoid having to check if there's a change to themes every time a new release is out.

**Comment by Luxocracy** [comment]
Hmm, yeah makes sense, perhaps I should look into it some more then for the short therm. But also, any new thing would end up falling back on the default values, so you would probably notice real quick as it would be out of place.

**Comment by hollo6** [comment]
Sure, but it would be even more inconvenient, especially if it happened at very bad times like in the middle of combat. :) Anyway it was just a suggestion, I'd appreciate if you could come up with a solution but I can live without it if it's too much effort.

**Comment by DogmaTX** [comment]
> What I can do and believe is the better solution is add an override folder. So I could make it so that if you place your textures in `Interface\NeatPlatesTextures\ClassWidget\` it will use those first, and if it can't find them it will revert to defaults.
> 
> This way you won't have to change them everytime there's an update.

It's working, thank you very much.
