### ISSUE TITLE
Nameplates turn blue

### ISSUE THREAD

**Issue by Groar90** [Luxocracy/NeatPlates#122]
Any idea why all nameplates turn blue when I get in combat? Can't find any option to change that behaviour.

**Comment by Luxocracy** [comment]
Well blue would indicate the the mob is "safe", aka attacking you if you are a tank, or not attacking you if you are a dps. Usually this is handled automatically, but wasn't working properly until the latest release.

You can force your role to tank or dps under _Threat & Highlighting > Threat Mode_ and you can change the colors under _Reaction_

**Comment by mawmaw1** [comment]
Before updating to the latest version I would always see the red indicator with spikes when I had aggro on a mob. Now it seems inconsistent and I don't always get the red indicator/spikes when I have aggro on mobs. Is this intended behaviour or what happened between the versions? Thanks for a good addon!

**Comment by Luxocracy** [comment]
This would be due to the implementation of the new threat lib for classic. When implementing it I removed the old _workaround_ for showing aggro as that is how it is on retail. However, turns out the threat lib isn't as accurate as it seemed during initial testing.

In the newer versions this should be working as it previously did with it showing an aggro warning if a mob is targeting you regardless of what the threat says.

**Comment by mawmaw1** [comment]
Okay but is it working as intended in the latest release, or is something funky still going on?
Maybe I'm just not understanding how the difference in the nameplate color is supposed to be working.

If you take a look at these four screenshots, sometimes the nameplate bar is red when the mob is aggroed towards myself, sometimes it is red when the mob is aggroed to a person in my group, sometimes it is blue when it is aggroed to either myself or others. It feels a bit inconsistent in behavior, whereas in a previous version the nameplate was always red with spikes when a mob was aggroed towards myself, and blue when not aggroed.

![issue1](https://user-images.githubusercontent.com/14732320/64759339-20b28a00-d537-11e9-9f70-097575039094.PNG)
![issue2](https://user-images.githubusercontent.com/14732320/64759340-20b28a00-d537-11e9-8703-2fb7878b8271.PNG)
![issue3](https://user-images.githubusercontent.com/14732320/64759349-25773e00-d537-11e9-8e75-b99549471f33.PNG)
![issue4](https://user-images.githubusercontent.com/14732320/64759350-25773e00-d537-11e9-8afe-a76fff074e17.PNG)

**Comment by Luxocracy** [comment]
Were you in defensive stance in any of those screenshots? Because the automatic threat mode is currently very simplistic in classic when it determines if you are a tank or does.

I would recommend swapping away from the automatic mode, and setting it to either tank or dps for a more consistent experience. If this was the issue that is.

**Comment by mawmaw1** [comment]
I just double-checked, and I was in Battle Stance in all of the screenshots. I'll try setting the mode to Tank for me and DPS for my teammate and see if that helps! Thanks.

**Comment by Luxocracy** [comment]
Hmm, that shouldn't happen then. I'll look into it and see if there's something weird going on with warriors as I've never experience this.
