### ISSUE TITLE
NeatPlates doesn't work in Groupcontent (Classic WoW)

### ISSUE THREAD

**Issue by MadHatter3424** [Luxocracy/NeatPlates#131]
Just like the title suggests, NeatPlates is not working for me as soon as I join a group. It switches immediately to the Blizzard default style (where for some reason the bar is always at 3/4th even when players are at full health).

The curious thing is, that outside from group/dungeon content NeatPlates is working pefectly fine and looks and does great! Maybe you can help me with this. 
Here is the List of Addons that I'M using. Maybe there is some kind of overlap with other addons that I'm not aware of:
ACP
Atlas
Atlas_ClassicWoW
Classic Aura Durations
Classic Castbars
DBM
DejaClassicStats
Dominos
Healbot
Leatrix Maps
Luna Unit Frames
NeatPlates
OmniCC
OneBag
Quartz
RealMobHealth
Recount
vendorPrice
WeaponSwing Timer

Thanks in advance!

**Comment by Luxocracy** [comment]
Friendly nameplates cannot be altered in dungeons/raids.
It showing 3/4 full is probably due to the nameplate texture used by the "Blizzard" style of plates have the same name as the default ones but are slightly different. This should be fixable if I just rename them, so it will hopefully be fixed in the next version

**Comment by MadHatter3424** [comment]
Thank you very much for the quick reply!
I see now, a shame that it doesnt work in instances, but it cant be helped I guess. 

Still, thanks a lot!
