### ISSUE TITLE
Scaling?Alignment issues.

### ISSUE THREAD

**Issue by dreamscape89** [Luxocracy/NeatPlates#146]
Hello,

It seems there is some kind of issues with the straight alignment of the bar.
Seems like a border issue? Seems like the border and the health bar overlap or something. And seen it present on multiple themes.

The name plate just does not look straight.

https://i.imgur.com/Pr93eLL.png

Also as a few suggestions.

1) Possible to add more customization to the font? Like moving the position of the Name text, under or above the bar. Or font size, font choise, font outline. etc. (especially would be nice to be able to select the under or above position of the font.
2) More customization to the cast bar. Position, size, font, icon etc.

**Comment by Luxocracy** [comment]
I can't say that I've ever seen the issue about the bar not being straight, nor am I able to reproduce it. So I would need some more information of when it happens and how etc, if possible as I'd be chasing ghosts otherwise.

As for more customization, it is something that is planned but I've yet to find an implementation that I've been happy with. But it is something I'm working on.

**Comment by dreamscape89** [comment]
Please let me know what kind of information you need. I am more than willing to share anything you need since this addon is awesome and want to see it working with no bugs.
