### ISSUE TITLE
Alvara level text default setting if class icon is disabled

### ISSUE THREAD

**Issue by Jezz1e** [Luxocracy/NeatPlates#161]
The level text for the Alvara theme clips when it has a long name. I suggest putting the level on the right side of the health bar. I really only use Alvara theme because it really looks clean but the level clipping is what's bothering me.

**Comment by Luxocracy** [comment]
Can't really move it to where you suggest because that's where the class icon appears if you have that enabled. I could potentially shorten the amount of space the name has so that it won't overlap, but this would cause longer names to have trailing dots to them.

But really what I see this issue as is that you currently can't re-position the level element through options. Which is something that will be possible once I finish the new customization options.

**Comment by Jezz1e** [comment]
Actually I fiddled with the code and got it to where I wanted to, since I don't use class icon anyways. However, I agree that the issue is that it should reposition when you enable class icon and that the default should have the level on the right side of the bar. I'll be renaming the issue and you decide whether to keep this open.
