### ISSUE TITLE
/nptank to persist through /reload

### ISSUE THREAD

**Issue by hasnogaems** [Luxocracy/NeatPlates#171]
Love ability to set tank manually, but it resets with every ui reload.
Any way to make it save names forever?

**Comment by Luxocracy** [comment]
I don't think there should really be any problem with making tank roles persist through a reload or even a complete restart of the client.
But I wouldn't want to make them persist forever, even when outside of a group, because players roles can change and I can see it getting out of hand after a while if the _list_ never clears. So I would still like it to clear when leaving/joining a new group to avoid issues in the future.
