### ISSUE TITLE
feature request 

### ISSUE THREAD

**Issue by mostoxic** [Luxocracy/NeatPlates#179]
@Luxocracy  However, once the new customization options are finished you should be able to move and resize pretty much every element of the nameplate. Which should allow you to make it look much more like the ElvUI nameplates.
was wondering if you had a time line on when this would be available for live thanks in advance!

**Comment by Luxocracy** [comment]
I'd say it probably depends on what state I would be willing to create an initial release at. But also it depends on when I can find the time to actually do it.

Because it currently does almost everything it's supposed to. It just isn't as easy to use as I'd like it to be, and I'm mostly worried about the off chance that I'd have to change how the data for it is handled to achieve that. Which would just become a headache for both sides if it was already released.
