### ISSUE TITLE
Green confirmation aura of the trading window disappears after NeatPlates is enabled in WoW Classic

### ISSUE THREAD

**Issue by SwimmingTiger** [Luxocracy/NeatPlates#180]
After NeatPlates is enabled in WoW Classic, if you click "Trade" button in the trade window, the green overlay on the transaction item list will show and soon disappear.

Under normal circumstances, the green overlay should last until the end of the trading.

I have tested NeatPlates 1.13.2.45 and 1.13.2.48, both of them have the same issue.

This video shows the problem:
https://www.youtube.com/watch?v=xTLIq2hS_IM
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/xTLIq2hS_IM/0.jpg)](https://www.youtube.com/watch?v=xTLIq2hS_IM)

WoW Classic with `enUS`. Clean WTF folder. No other addons. (`zhCＮ` has the same issue.)

**Comment by Luxocracy** [comment]
Managed to track down the issue so should be fixed in the latest release.

Basically the 'Range finder' lib that is used in the addon calls the 'GetItemInfo' function, which triggers an event('GET_ITEM_INFO_RECEIVED'), which the trade frame for some reason listens for in Classic but not on retail.
Not really sure for what reason it would listen for that event, but found it interesting that blizzard deems this necessary in Classic but not retail...

**Comment by SwimmingTiger** [comment]
I think the problem has been fixed in 1.13.2.49. I no longer have this issue after updating.
