### ISSUE TITLE
Clickable area for nameplates is out of place

### ISSUE THREAD

**Issue by Srljm** [Luxocracy/NeatPlates#183]
Hi.

My nameplates are not working as expected.
It seems that the horizontal clickable area is extended to the right, not correctable by any settings.
What I have seen is that the same goes for the default neat plates settings:

![NeatPlatesClickableAreaBug](https://user-images.githubusercontent.com/55985046/70846815-888daf00-1e5d-11ea-9e1d-01e42dae83cc.jpg)

You can see that my mouse cursor is far right to the target "Hoebert". A slight glow indicates he is still my mouseover target while standing not nearly enough where my mouse is.
The top right picture shows the current adjusted clickable area, it matches the nameplates exactly.

The other screenshots are my relevant settings, but using the default settings seems to have no change for this.
Do you have any suggestions what causes this?

**Comment by Luxocracy** [comment]
Hmm, there's definitely something weird going on with nameplates in classic. It's like there is two separate areas for clicking but one is offset to the right for some reason. Because with both sliders at a 100% you can tell there's a gap at the top right that doesn't make any sense as it should be a rectangle.
To borrow from your illustration of the issue, I think it's actually something like this. Where there are two rectangles overlapping.
![70846815-888daf00-1e5d-11ea-9e1d-01e42dae83cc](https://user-images.githubusercontent.com/2884542/70847668-2174f800-1e67-11ea-8f47-a0512433bb86.jpg)

The problem is, I'm not sure if there is anything I can do about this as the function that we have access to that allows us to modify the clickable area is one defined by blizzard through the API.

**Comment by Srljm** [comment]
Been a while since this report, but unfortunately still persists with TBC.

I have seen this problem in "Plater" too, but it hasnt appeared at first, only after I touched certain settings to adjust width and height. After that it wouldnt go away.

Back to Neatplates, I noticed there is a way to temporarily get rid of this extra wide clickable area:
1. first set clickable height of nameplates to 200% and reload the game
2. reduce the clickable height to around 100%. The area is gone.

This holds until I reload the game. At this point I can also repeat the steps from 100 to 60, and its gone again. Then 60 to 10% or just back with 200 to 100, you get the idea.

Can you implement an order of executions like this when the addon loads? For example it starts with an high value of 500% and immediately goes down to the value in the setup. Maybe this works as a fix for the issue.

**Comment by Luxocracy** [comment]
Actually haven't noticed this at all, but I'll see what can be done if this does indeed fix it.

**Comment by Luxocracy** [comment]
I think I fixed it, I have no idea why what I did works. But it seems to work.

Couldn't get your solution do work through code, but I noticed the size seemed to be set correctly if a plate was on screen when reloading. And I also set a 100ms delay before setting the sizes, no idea why it works, but it seems to need both to work.

**Comment by Srljm** [comment]
Very good, no issues so far. Thanks a bunch.
