### ISSUE TITLE
Text in threat indicator do not display correctly

### ISSUE THREAD

**Issue by alexqu0822** [Luxocracy/NeatPlates#188]
Files:  \NeatPlatesWidgets\ThreatPercentageWidget.lua
          \NeatPlatesWidgets\ThreatLineWidget.lua

Text in threat indicator do not display correctly because 'local font = "FONTS\\ARHei.ttf"' does not fit for non-latin language.
Maybe you can change it to 'local font = GameFontNormal:GetFont()'

**Comment by Luxocracy** [comment]
There's no font named "ARHei.ttf" used within the addon, so I just wanted to check if you perhaps meant "arialn.ttf". And in what way does it not 'fit'? Because this font is used for a couple of other things as well. 

And while this font will most likely remain the same for latin languages there is definitely the possibility of changing it for others.

**Comment by alexqu0822** [comment]
yeah, "FONTS\\arialn.ttf".
Maybe it exists in clients of all languge.
Fontstring using "FONTS\\arialn.ttf" can only display ASCII char.
It doesnot support characters of zhCN,zhTW. When playing in zhcn client, threat indicator  always show "????".

**Comment by Luxocracy** [comment]
Do aura durations work? Or does that also show up as '??'? Because that uses the same font and I find it weird that this issue hasn't been reported before if that font doesn't actually display numbers for zhCN and zhTW.

**Comment by alexqu0822** [comment]
Duration number works.
Name in threat indicator show up as "???".

**Comment by Luxocracy** [comment]
I've changed the font used in the latest release so hopefully this should now be resolved.
