### ISSUE TITLE
(Classic) Nameplate overlap values not showing up initially

### ISSUE THREAD

**Issue by Srljm** [Luxocracy/NeatPlates#189]
![NeatPlatesOverlapValues](https://user-images.githubusercontent.com/55985046/72364661-2abbe380-36f7-11ea-930b-95a4de99c8d3.jpg)

The values are only showing if I have adjusted the bars.

This is somewhat annoying since I cant remember what the settings are and by grabing the slider it snaps to the current mouse cursor position, meaning you almost always are a few values off once the numbers appear.
But I need those last values for comparison.

Can you make them always visible?

**Comment by Luxocracy** [comment]
These show up perfectly fine for me.
I do recall there being a point where I was having issues with them disappearing sometimes but that issue resolved it self somehow, and I haven't been able to replicate it since then

The CVar section is slightly different however as it relies on reading and setting the CVars directly instead of storing them in the addon settings. So I'll look into if I can get it to retry fetching the CVar from the server if it's value is empty.

**Comment by Luxocracy** [comment]
A \*fix\* for this was added a while ago so hopefully it is working as intended. If not just comment here and we can re-open this issue.
