### ISSUE TITLE
Colour by Threat mode seems to be buggy now

### ISSUE THREAD

**Issue by TomKuhn** [Luxocracy/NeatPlates#194]
I use NeatPlates on Threat mode as a tank: Attacking me = green, Attacking others = red. It has been working really well for months, but recently, even when mobs are clearly not even targetting me, they're showing green. Prime example is the twitchy skeletons in Scholomance just before Darkmaster, where they randomly go after other players, but the colour of the threatplate is green (I have aggro, when I clearly don't!)

**Comment by Luxocracy** [comment]
How recent is recently? Was it acting weird before the 15th of February(last weekend)?
Because that's the date I moved over to automatically include libraries, such as the threat lib, so that they would be more up to date.

Either way I can only assume this has something to do with the threat lib, if it is happening all of a sudden. As tanking threat relies entirely upon that lib to decide if you have aggro on something or not, as I've felt it would be incorrect to handle threat based on if a unit is targeting you or not for tanks. As opposed to a DPS role where I see it as acceptable to mark a unit as aggroed onto you when they are targeting you.

**Comment by TomKuhn** [comment]
Yes I think it's only just started happening in the last 2 updates 1.13.3.13 or 1.13.3.14. I'm going to roll back to 1.13.3.12 and see if the old behaviour returns.  I'm assuming some mobs although I have the most threat, are randomly targetting others (and before the bar would go red so I could taunt them back)

**Comment by TomKuhn** [comment]
No 1.13.3.12 is still very odd. I just tried it in a strat UD. Let a mage pull the mob off me by overaggro and the bar stayed green despite the mage was clearly highest on threat and mob targetting the mage. I'll go back further.

**Comment by Ham-eth** [comment]
This bug is still occurring, for me and 3 other tanks in my guild.
The threat plates do not update, you must click them to get them to change, they cannot be used to monitor threat any longer.

They used to work perfectly

**Comment by Luxocracy** [comment]
I've not made much progress in identifying why this happens, but I also haven't been able to get the issue to happen for me, not sure why.

But in the latest release I added a debug command `/npdebug threat` which prints the time between threat updates into the chat. So the next time you come across this issue I'd appreciate it if you could toggle that on and report back if it prints anything into the chat and if it does the average time it takes between updates.

Also, reverting to version 1.13.3.5 or earlier might help as this is the last version with the _old_ threat lib.

**Comment by Ham-eth** [comment]
The latest version seems to be better, i thought it had fixed but then i had some that did not update.
If a rogue in my group pulled it worked immediately, i noticed one warrior that it never updated for, even when i was targeting the enemy and hitting it with abilities, although taunt would usually update the color.

I ran /npdebug threat and it spammed chat with updates from 0.1 - 0.6 seconds, occasionally there was a 1.3 or 1.6

**Comment by Luxocracy** [comment]
Now that you mention it not working with some people but working with others. If I remember correctly the other people need to also use an addon with the same threat lib for it to update correctly. I'd completely forgotten about that...

Which is probably why I haven't had the issue myself. I'll look around and see what other addons are using now since the old one was "abandoned" to achieve the best compatability.

**Comment by Ham-eth** [comment]
ah that would make sense, so it uses the same threat lib as "details tiny threat" for example?
has it always required all parties having compatible threat libs runnings to communicate?

viewed from a user standpoint that didn't have any idea how it worked, when i first got it it was:
-OMG this is amazing worked flawlessly
-then it stopped working altogether where none of them updated 
-now it seems some update and some dont depending on the player who pulled threat

when i first got neatplates i dont think I even had an addon like details for threat meters and i was puggin alot of dungeons so i doubt everyone i pugged with all had an addon like that either
