### ISSUE TITLE
Duration displays incorrectly.

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#196]
![TIM截图20200314135455](https://user-images.githubusercontent.com/44251440/76680528-31e26d80-6624-11ea-86dc-a4988293c3a6.png)

When an enemy Paladin cast Divine Shield and then use Hearthstone, he will stay still for a while.
And the duration of Divine Shield displays incorrectly.

**Comment by Luxocracy** [comment]
Hmm, the game must be reporting the aura as existing even though it has expired, aswell as saying it will expire at a time that has already passed. Which results in a negative duration.

I'll double check if auras are properly getting ignored when they report a negative duration. Because if they are something else is going on.

**Comment by yishuangfrank** [comment]
It's an unimportant issue.

**Comment by Luxocracy** [comment]
I believe this should be resolved in the latest release. If an aura duration reports a negative value it should no longer display the duration, but the aura will still remain.

**Comment by yishuangfrank** [comment]
Thanks for your working!
