### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by larspensjo** [Luxocracy/NeatPlates#202]
The "Overview" of NeatPlates that I see when I click the addon from Twitch doesn't say what it is about. That should be the first thing you see.

**Comment by Luxocracy** [comment]
It's literally the first sentence.

> NeatPlates is a nameplate addon that works with both the Classic and Modern version of WoW.

**Comment by larspensjo** [comment]
What? That says nothing about what it is doing?

**Comment by Luxocracy** [comment]
I've never really felt the need to elaborate on what it does other than it being a nameplate addon.

It might just be because I usually end up picking addons through recommendation, images or minor details that aren't usually listed as features.

What kind of info would you like to see in the "overview"?

**Comment by larspensjo** [comment]
What is a nameplate?

**Comment by Luxocracy** [comment]
Are you asking? Or is that the kind of info you think should be there?

Because quite frankly, if the people browsing for addons don't know what a nameplate is, the addon probably isn't something they need right now. At least that's how I would view it.
