### ISSUE TITLE
NeatPlates causes Lua error every now and then

### ISSUE THREAD

**Issue by silverhawke249** [Luxocracy/NeatPlates#204]
After updating to new version, sometimes a Lua error would occur (seemingly when a new nameplate comes into view).
The pastebin link has a dump of the locals the first time it happened: https://pastebin.com/SgB6sb5z
Subsequent errors simply says `Interface\AddOns\NeatPlatesHub\functions\Color-Color.lua:292: Usage: UnitPowerType("unit"[, index])`.

**Comment by Luxocracy** [comment]
I've release an update that I believe should fix this issue. 

At least for the time being, this is similar to other issues that have happened in the past so it's probably due to some underlying issue with how the data loop currently works, where it occasionally tries to use values that don't yet exists. In this case the 'unitid' used to get the units powertype.

**Comment by silverhawke249** [comment]
I can confirm the most recent update as of now fixes the issue -- no Lua errors popping up so far.
