### ISSUE TITLE
Show self-resource near enemy plate (possible feature request)

### ISSUE THREAD

**Issue by bbarker** [Luxocracy/NeatPlates#205]
Say you're a a rogue: this would allow you to see your energy bar near the enemy's neat plate, so you don't need to look elsewhere on screen when deciding what action to take next.

**Comment by Luxocracy** [comment]
This has been requested before and I decided against it purely because I believe it would be confusing.
Especially after recently adding the option to display the units resource on the nameplate.

I also know that this is achieveable by using weakauras to attach a simple resource bar to the nameplates. So if this is something you really want it is possible, but I don't have any links to any working WAs that do this on hand.
