### ISSUE TITLE
Huge FPS drops

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#207]
Hey Lux,

I´ve been experiencing huge fps drops in fights like Carapace and N'Zoth due the big a amount of adds. There is some moments in these fights that a huge pack of adds would spawn and when they stack my fps goes down.

I´ve tested those fights with the standart nameplates and it goes smooth.

Any ideas?

Thx in advance.

**Comment by Luxocracy** [comment]
Is this a recent issue? As in this week?
Because then it could be related to the new resource bar as it might be triggering updates even when not used. But it really shouldn't have had a big impact.
Auras is definitely a big one when it comes to performance. Reducing the amount of auras displayed at once should help. Also setting the _Precise aura duration threshold_ to 0 should drastically improve aura performance.

But just in general, balancing performance and features is one of the trickiest things about maintaining an addon.

**Comment by Diablolock** [comment]
Actualy It's an issue since the new raid release.

The Precise aura duration threshold was set to 10. The range check indicador was on and the absorb bars as well.

I will test it out on next reset and let you know.

Thx for the recommendations.

**Comment by n-r-w** [comment]
Same issue on Sire Denathrius and Sun King's Salvation

**Comment by Luxocracy** [comment]
Anytime there's a lot of nameplates on screen it will inherently impact performance, if it's a big issue try to reduce the amount of features/widgets that are enabled as previously stated.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
