### ISSUE TITLE
Lately color change of nameplate have been randomly very delayed

### ISSUE THREAD

**Issue by hasnogaems** [Luxocracy/NeatPlates#217]
Sometimes color change is instant but sometime it like stuck. Change eventually but like after 5 sec. Did something changed recently? I first noticed it like a 2 weeks ago.

**Comment by Luxocracy** [comment]
No, nothings changed related to threat. I think this is just down to the classic threatlib not being perfect, and it probably never will be either. But seemingly it might be more dependent on others having the addon now than it was previously, at least from what I've seen.

**Comment by hasnogaems** [comment]
I thought before it was based sorely on target. If target not tank it will go red. And it semmed that it worked that way. Color was changing even for brief moments when enemy was casting something on offtarget, with no threat loss happening.
Is there a way to simplify this coloring behavior to just be target dependent, not threat dependend?

**Comment by Luxocracy** [comment]
For DPS this is what it does, it prioritizes if you are the target before checking threat. For tanking on the other hand, just because a mob isn't currently targeting you doesn't always mean you've lost threat. They might just be casting a spell on another unit as part of their mechanics. Which is why it doesn't have the same kinda of prioritizing that it does for DPS.

It could be changed, but I don't see a point in it because, as far as I can tell, the next patch will enable the normal threat API that exists in retail. Because threat addons are causing a lot of chat spam by communicating with each other and I believe they even throttled it at times. Which could be the reason behind the delay in threat updates.
So once the patch comes out threat should become really stable again. Hopefully.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
