### ISSUE TITLE
nameplateOccludedAlphaMult option.

### ISSUE THREAD

**Issue by Revnn** [Luxocracy/NeatPlates#229]
Hi, would it be possible to add an option to change nameplateOccludedAlphaMult?
i tried to use this script command /run SetCVar("nameplateOccludedAlphaMult",0) that work on other nameplates but didnt work with neatplates.
What im trying to do is to set that to zero, so i dont see nameplates through walls.
Thanks.

Edit: Oh and there is a way to change the font of the nameplates? i only see the option to use blizzard's font, but not custom ones. 
Edit2: I actually found a work around on the font, i removed all fonts from \NeatPlatesHub\shared leaving only the one i like and it worked. But would be amazing to be able to swap fonts inside the ui.

**Comment by Luxocracy** [comment]
As far as I know the client doesn't know if a unit is in line of sight or not, so in order to add _support_ for this CVar it. I believe it would have to overwrite all of the _Opacity/Alpha_ options that currently exists in the addon and rely entirely on the alpha set/used by blizzard nameplates.

If you have an example of another nameplate addon doing this, as you mention _"other"_ nameplates, I can look into how they do it and see if I've missed something and if it can be impletemented into NeatPlates.

As for fonts, it's something that's been requested before and will most likely happen at some point. But because some themes can use a few different fonts for different aspects it is something that will take some time to separate into categories to allow for easy font swapping.

**Comment by Rhess86** [comment]
Cool, please check it out because thats the only thing bothering me atm, after i checked out the other nameplates i've seen what a great QOL is, specially in some places like tol dagor.
Kuinameplates can do it, they even have a built in option on the ui.
Even elvui's native nameplate work with the command.

**Comment by Revnn** [comment]
I saw the latest update you added a Blizzard Name Visibility option, does it have anything to do with this request?

**Comment by Luxocracy** [comment]
Sadly no, I've yet to find the time to properly look into this.

**Comment by Luxocracy** [comment]
So I decided to look into this, as I had some time, and seems I was kind of thinking about this in the wrong way. Where this can be used as a multiplier, without interfering with the current alpha/opacity options, as opposed to my original thought which was that it would have to overwrite the alpha.

Which made it a rather simple to implement and I've pushed a new release with this change in it. Although I've only lightly tested it so please do update me if you see any weirdness with it.

**Comment by Revnn** [comment]
Hell yes, working perfectly, you are the best. Thanks \o/
