### ISSUE TITLE
General Aura Filters - idea

### ISSUE THREAD

**Issue by yah467958** [Luxocracy/NeatPlates#232]
Hello

I just wonder if it possible to make normal auras/emphasized auras size do adjustable? It would be nice to change size of buffs/debuffs on our own.

Also DK buff ''Anti-Magic Shell'' doesn't appear over healthbar after added to general aura filters.

**Comment by Luxocracy** [comment]
Sorry for not responding to this, it kinda slipped my mind...

Just to make sure what you are looking for, do you just want to alter the general size of the normal/emphasized auras? As currently exists for normal auras but not emphasized ones. Or are you looking to individually alter the size of certain auras, such as making _Fear_ 50% larger than the other auras?

Because adding an option for the scale of _Emphasized auras_ isn't much trouble, but controlling them individually would require a change in how the you define the auras. Which is something is needed, as the current method is rather basic, but I can't say when it will happen.

**Comment by Luxocracy** [comment]
Oh and also, for the _"Anti-Magic Shell_ did you give it the **all** prefix? If you did, you can try using the SpellID instead (48707, I think that is it, but not entirely sure)

**Comment by yah467958** [comment]
No worries mate, its all right.

What I mean is to change size of normal/emphasized auras on our own, like it is in flyPlateBuffs addon for example. So we can adjust width/height how we want to. Of course it would be awesome to have some extra options like adjusting size of our own auras, or individual auras. I hope this makes some sense what I've just wrote :S

Oh yea... forgot about SpellID gonna try with it. Cheers

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
