### ISSUE TITLE
Other Widgets

### ISSUE THREAD

**Issue by Reydas** [Luxocracy/NeatPlates#233]
Thanks for the cool addon. After the latest updates, the ability to customize class icons on the health bar, namely Personal Resource Style as before, has disappeared. You change the values, but the icon does not move, please return this opportunity.

**Comment by Luxocracy** [comment]
If you are referring to the button that used to exist under the _Class Icon_ & _Personal Resource_ options. This was removed because they were redundant, as the option to move these now exist in a better form in the _Theme Customization_.
If this isn't what you were referring to, as you also mention changing the values and the icon not moving. Make sure you are editing the correct profile when in the _Theme Customization_, because I couldn't find any issues with them when I tested it out.

**Comment by Reydas** [comment]
![image](https://user-images.githubusercontent.com/65668304/86538914-cc332d80-bf01-11ea-9122-7d778d73b856.png)
where can you customize the class icon as you wish? its size and position relative to the strip of life above the enemy’s head?

**Comment by Luxocracy** [comment]
Interesting, could have sworn I had removed the button for _Personal Resource_ as well, but at the bottom of the profile page there's a button labeled _Theme Customization_, from there you can find this under the _Widgets_ section.

**Comment by Reydas** [comment]
Found it, thanks!
