### ISSUE TITLE
Skyfury Totem's customized color would taint all rival nameplates

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/NeatPlates#243]
I use the same config for Grounding Totem and Skyfury Totem, as below
```
#FF4500 根基图腾 //Grounding Totem
#FF4500 天怒图腾 //Skyfury Totem
```
Both totems are correctly colored but the Skyfury Totem would cause all rival nameplates to be FF4500. I don't know whether it's a bug of NP or it's related to how Skyfury Totem works with nameplates. Please look into this when convenient, thx!

**Comment by Luxocracy** [comment]
I wasn't sure at first what might cause this, but it's because the Skyfury totem is both a unit and a buff. 

The best solution would probably be a re-work of the system, which is something I've wanted to do. But it's been hard to find the time for it, as well as the multiple other systems that I'd like to re-work competing with that time.

Short term, I think the only solution is to add a prefix like **'unit'** as I was already in the process of adding prefixes for auras to distinguish from your own auras and others to the color conditions.

**Comment by Nukme** [comment]
Hi, I have tested the newest update. The 'unit' prefix could help distinguish between buffs and units. But there's bug that prevents multi-line config from working. Say I set the color conditions to be
```
unit #FF4500 Grounding Totem
unit #FF4500 Skyfury Totem
```

The second line would correctly recognize the 'unit' condition and prevent tainting, but the Skyfury Totem is not colored(default red).

**Comment by Nukme** [comment]
More tests suggest that the first line of 'unit' prefix would break the lines below it.
```
unit #FF4500 Skyfury Totem
#FF4500 Grounding Totem
#FF4500 Capacitor Totem
```
Set the conditions like this and the two totems below Skyfury Totem would not be colored (default red).

**Comment by Luxocracy** [comment]
I accidentally stopped checking further color conditions for the unit completely instead of just skipping the line/condition if it had the _unit_ prefix and it didn't match. Should be fixed in the latest release.

**Comment by Nukme** [comment]
Cool, it's working now. I'll help with the localization on curseforge.
