### ISSUE TITLE
Chi/Combo Point

### ISSUE THREAD

**Issue by KumaNekoi** [Luxocracy/NeatPlates#252]
After the pre-patch and updating the addon to the newest version, I no longer see Chi count on the nameplates. Tested on a rouge as well, and no combo points are shown either.

**Comment by Luxocracy** [comment]
Double check that the personal resource option is set correctly.

**Comment by Shadowmastr** [comment]
Can confirm going to Interface -> Names -> Enabling Personal Resource Display, then enabling Show Special Resources on Targets worked for me (can disable Personal Resource Display afterwards if you only want to see the combo points/chi instead of the Personal Resource Display bar). However, the combo points look very different than when they did before using the Quatre setting. Images attached. Is there any way I can change a setting to make the combo points look like the old ones? They were much cleaner, and were integrated below the nameplate instead of above the nameplate. Thanks
![NeatPlatesOldCP](https://user-images.githubusercontent.com/72906585/96082092-9c90ab80-0e88-11eb-8df1-1cd4ec379ebe.png)
![NeatPlatesNewCP](https://user-images.githubusercontent.com/72906585/96082119-a3b7b980-0e88-11eb-8194-ef8a1067dfc2.jpg)

**Comment by Luxocracy** [comment]
Try enabling personal resource in your profile settings rather than the interface options. That's the setting I was referring to earlier. I'm a bit surprised the interface option even did anything tbh.

**Comment by Shadowmastr** [comment]
Thanks for the quick reply and fix! This makes a lot more sense now. Here's an image of how the setting should look in the Neatplates Interface options (it is near the bottom of all of the options hidden in the dropdown you described). Just had to check this box, and all was back to normal.

Thank you again!

![NeatplatesPersonalResourceSetting](https://user-images.githubusercontent.com/72906585/96085066-3c9d0380-0e8e-11eb-9870-388f226a8b57.jpg)

**Comment by KumaNekoi** [comment]
Thanks for the reply, I'll try it as soon as I get home, and close it then.
Was playing around with it yesterday, but guess I never found the correct setting.
Sorry for troubling you.

**Comment by Luxocracy** [comment]
No worries, I've also pushed a new release that should fix this issue as it's supposed to be enabled by default. As quite a few people seem to use mostly default settings.

**Comment by KumaNekoi** [comment]
The issue was indeed fixed in the update. Thanks for the quick response and the quick fix.
