### ISSUE TITLE
minimum/maximum alpha (distance)

### ISSUE THREAD

**Issue by ANaPhOrAX** [Luxocracy/NeatPlates#268]
This seems VERY buggy. I've tried playing around with these, and they don't seem to really be working as intended.

Some notes:

1. minimum alpha doesn't seem to even work at all if set to anything above 0.5
2. occluded alpha multiplier seems to not work if higher than the minimum alpha
2. if minimum alpha distance is supposed to change at what distance it switches to minimum alpha, and maximum alpha distance is supposed to be when it changes to maximum alpha, then theoretically the minimum alpha setting should be higher, right? example: I have minimum alpha distance set to 40 yards. meaning that at 40 yards, the nameplates will take on minimum alpha; in this example, let's say 0.5 opacity. then, once I get closer and reach maximum alpha distance at 20 yards, the opacity will be 1.0, or 100%. but this doesn't seem to be at all how it's functioning atm.

What am I missing here? Very confusing.

**Comment by Luxocracy** [comment]
The behaviour of these CVars is set and controlled by Blizzard, I simply pull the alpha/opacity straight from what the normal nameplates would have when these CVars are changed, and multiply them with the addon opacity settings.

However, it does seem like an event I was using is no longer firing properly. There was also a check in place to see if the alpha from the normal plates were to be used or not, which was probably a left over from when initially I only added support for the Occlude Alpha Multiplier. Which is why it never went above 0.5 for you, as the event for this setting wasn't firing properly.
So these issues might account for some weirdness and they should be fixed in the next release, however, it might not account for your third point.

The way I see them working is
- Any distance below the _Minimum Alpha Distance_, will set the alpha to the _Minimum Alpha_
- Any distance abovethe _Maximum Alpha Distance_, will set the alpha to the _Maximum Alpha_
- _Minimum Alpha Distance_ overrides _Maximum Alpha Distance_ in case both were to occur

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
