### ISSUE TITLE
Pool of Mixed Monstrosities Nameplate Bugged

### ISSUE THREAD

**Issue by bilbo-laggins** [Luxocracy/NeatPlates#269]
In Maldraxxus at 58, 73 there is a pool that requires goo to be placed in certain configurations to spawn rares. The way you tell what to do is the name plate will show you how many of each color are already in the pool. For some reason NeatPlates breaks this functionality and the nameplate will just say unknown under it. Other nameplate addons like TidyPlates for example didn't have this issue when I tested so I'm not sure which part of this addon breaks it.

**Comment by Luxocracy** [comment]
This is because NeatPlates has it's own way of displaying some nameplate _widgets_ like this, which was added because of  much simpler _widgets_ like this in BFA. But they expanded a bit on the concept for Shadowlands and I thought they'd made them all different IDs for they type, however, it seems like this one especially is using the same _typeID_ as the ones they had it BFA.

I'll expand the option to use _Blizzard Bar Widgets_, which is already enabled by default, to catch all widget types instead of just some. So I'll have this fixed asap.

**Comment by bilbo-laggins** [comment]
Awesome thanks!

**Comment by Luxocracy** [comment]
The fix should be available shortly on curse.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
