### ISSUE TITLE
New Font

### ISSUE THREAD

**Issue by Revnn** [Luxocracy/NeatPlates#272]
Hi, I'd like to make a request.
Please add the feature to change fonts/add custom font.
I already do it manualy, but everytime the addon is updated i have to do it all over again.
What i've been doing:
Pasting the new font inside NeatPlates\media and replacing the DefaultFont.
Pasting the new font inside NeatPlatesHub\shared and deleting all other fonts.
Editing Neon.lua line 6:
--local font = "Interface\\Addons\\NeatPlatesHub\\shared\\(name of the new font).ttf"; local fontsize = 12;

Since you update your addon quite often, which is a good thing, its getting quite tiresome for me lol
I really appreciate the help.

**Comment by Luxocracy** [comment]
This is a feature that's been requested quite often, and it is something that I'd love to get done. However, it would be a really time consuming feature to add, in part because of how the Theme system is currently set up. So I can't say that I'll get to this any time soon.

But what I would recommend you do is to make a new Theme out of the Neon one. I can help you out if you need any help, but it should be pretty simple to do.

I'll attach a modified version of the Neon theme with the name replaced, so anywhere it says _MyTheme_ just rename it whatever you'd like. Both in the .lua and .toc file.
[NeatPlates_MyTheme.zip](https://github.com/Luxocracy/NeatPlates/files/5660719/NeatPlates_MyTheme.zip)

**Comment by Revnn** [comment]
So the theme doesnt get updated and the font will never change?
But wont that get in the way of some future update?

**Comment by Luxocracy** [comment]
It won't get overwritten when there are updates. However, as you mention, any new features that get added and require modifications to the theme files could require your to update your custom theme as well. But there is a default theme that it will fallback on if these features aren't defined in a theme, they would probably just not appear in the correct positions.

Although the themes aren't updated very often as most features don't require it.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.

**Comment by Diablolock** [comment]
@Luxocracy I tried what he said about changing the font but I only could make it to the NAME on nameplates.

Is there a way to manually change the font of the timers/stacks of DOTs?
