### ISSUE TITLE
pandemic highlight issue

### ISSUE THREAD

**Issue by Nucrox** [Luxocracy/NeatPlates#278]
Enable pandemic highlight doesn't work properly for me. 
First of all it doesn't highlight on the last 30%. it only highlights around 10-15-20%. it seems like its random among different abilities. (i.e. 18sec agony highlights at ~3.5sec remaining)

Also if i refresh the debuff, it doesn't even highlight at all once it's about to expire sometimes.

**Comment by Luxocracy** [comment]
Seems something was indeed broken about this, it was only ever updating when something else was updating, ex. when taking damage from something like a dot tick etc. Which is probably why I've never noticed it as it would be correct when a lot of updates where happening.

This should be fixed in the latest release however and it should now properly update the highlight at the correct times.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
