### ISSUE TITLE
Castbar customization

### ISSUE THREAD

**Issue by nakinacho** [Luxocracy/NeatPlates#282]
I am a tank and I use your addon in dungeons, but when all monsters are casting, their castbar blocks the healthbars vision.
Can you make more customization for the castbar, for example, reduce the size.
Thank you.

**Comment by Luxocracy** [comment]
This can technically already be done through the _Theme Customization_. Although I do understand that because the castbar is comprised of several different elements I can be a bit bothersome to do so. And at some point this will hopefully be condensed into a single, or at least less, elements that have to be edited and moved around. But I can't really give a timeframe for when that will happen.

**Comment by nakinacho** [comment]
https://i.imgur.com/Q3Tz7JX.png

I tried, but could not make the border and bar the same size.
I found only 3 lines in settings for the castbar, maybe there is more.

**Comment by Luxocracy** [comment]
In some cases, due to how some textures are set up, you would have to also adjust the _Offset Y_ position of them. The castbar border is one of these cases. The _Theme Customization_ system is essentially still in alpha and hasn't had much improvements made to it, in part due to issues like this with textures, but also because there are slight differences between themes in general. Which makes it harder to do as an overall system without changing somethings about how themes are currently set up.

If you don't have any other _Theme Customizations_ right now here's an import string with a smaller castbar height set as an example, just so you can see what I mean.

```
^1^T^SNameOnly^T^t^SDefault^T^Scastnostop^T^Sy^T^Svalue^N11^Stype^Soffset^t^Sh^T^Svalue^N-28^Stype^Soffset^t^Senabled^T^Svalue^B^Stype^Sactual^t^Sx^T^Svalue^N0^Stype^Soffset^t^Sheight^T^Svalue^N-28^Stype^Soffset^t^Sanchor^T^Svalue^SCENTER^Stype^Sactual^t^Sw^T^Svalue^N0^Stype^Soffset^t^Swidth^T^Svalue^N0^Stype^Soffset^t^t^Scastborder^T^Sy^T^Svalue^N11^Stype^Soffset^t^Sh^T^Svalue^N-28^Stype^Soffset^t^Senabled^T^Svalue^B^Stype^Sactual^t^Sx^T^Svalue^N0^Stype^Soffset^t^Sheight^T^Svalue^N-28^Stype^Soffset^t^Sanchor^T^Svalue^SCENTER^Stype^Sactual^t^Sw^T^Svalue^N0^Stype^Soffset^t^Swidth^T^Svalue^N0^Stype^Soffset^t^t^Scastbar^T^Sy^T^Svalue^N4^Stype^Soffset^t^Sh^T^Svalue^N-6^Stype^Soffset^t^Senabled^T^Svalue^B^Stype^Sactual^t^Sx^T^Svalue^N0^Stype^Soffset^t^Sheight^T^Svalue^N-6^Stype^Soffset^t^Sanchor^T^Svalue^SCENTER^Stype^Sactual^t^Sw^T^Svalue^N0^Stype^Soffset^t^Swidth^T^Svalue^N0^Stype^Soffset^t^t^t^SWidgetConfig^T^t^t^^
```

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
