### ISSUE TITLE
Absorb widget height adjustment

### ISSUE THREAD

**Issue by Bodify** [Luxocracy/NeatPlates#287]
Hey! I've been trying to make my own theme and the only part I've ran intro struggle with is the absorb bar widget. Adjusting the height offset in theme customisation does nothing and I've also tried increasing the height of the Absorb.tga file in the relevant theme but it seems locked into a certain position no matter how big I make it.
![image](https://user-images.githubusercontent.com/79547183/108919987-371daa00-7634-11eb-8825-7512a6aaba66.png)

I also noticed that the "Mouseover Highlighting" is also not being able to adjust via Offset Y in the settings (but I worked around this by just editing the tga file.

**Comment by Bodify** [comment]
After fidgeting with this for awhile I realize that it requires a UI reload for the addon settings to load but it seems picture height doesnt matter? Second issue I'm having now is that it seems absorb widget's frame strata (?) is above the healthbar border. Shouldn't that be under? It's looking a bit weird as is for me now.

**Comment by Bodify** [comment]
![image](https://user-images.githubusercontent.com/79547183/108923548-55d26f80-7639-11eb-99a8-aa6ae480f204.png)
This was the best I could manage to make it. You can see it's a pixel or two off. But if I adjust it up it covers the border more than what it does at the bottom. Trying do edit the tga file a pixel didnt help me either. Anyway I could make the absorb show below healthbar border?

**Comment by Luxocracy** [comment]
You can set half pixels by clicking on the number for the slider and writing it in. I don't know if that would help in this situation but it might.

As for the absorb widgets frame strata the way it's currently set up with the absorb widget being it's own separate entity. I don't believe it's possible. This is because the border is a texture within the healthbar frame. So the absorb widget would have to be part of the same frame essentially to do this.

The _Theme Customization_ is still in a very early stage and I haven't really had the time to work on it. Which is why it's in a rather incomplete state right now with not all things working, especially for the widgets. Hopefully I can find time at some point to complete this, but it's rather low on the list.

If you'd like more control over this currently I'd recommend you _actually_ make your own theme, I mention how to go about doing it in this issue(https://github.com/Luxocracy/NeatPlates/issues/272). If that is something you end up doing, I'd be glad to help if you feel the need for it.

**Comment by Bodify** [comment]
Thanks I was not aware I could click the number and adjust by half pixels. It's still a bit wonky but at least it is better now! I have made my own modified theme now so thanks for saving me that headache if I accidentally updated the addon without backup'ing the edited theme! While I'm still playing around with all the settings and trying out different looks I am running into some issues here and there. One being even though the castbar border here is an uncompressed tga file it seems to produce some artifacts around the border ingame. I've double checked and there are no actual artifacts in the file. 
![image](https://user-images.githubusercontent.com/79547183/109262462-df349e00-7801-11eb-8978-1b0f401f699c.png)

Any idea how I can work around this and the cause of it so I can try avoid it?

While I'm here can I also ask if there is a way to make a castbar backdrop? Having the castbar see through can cause it to be hard to read/see in some cases.

**Comment by Luxocracy** [comment]
Whenever I've noticed artifacts on things it has usually been because of the alpha channel, so I'd start with checking that at least. And then, if possible, check what tga export settings you are using, because I think I had issues with the RLE compression option at some point for wow.

As for a backdrop you'd most likely have to specify one in the theme files, in the castbar prop, as I believe most themes just uses and empty texture as a backdrop. But it should be supported if one is specified.
![Capture](https://user-images.githubusercontent.com/2884542/109326892-028a3800-7858-11eb-8a49-183ba53b4b78.PNG)

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
