### ISSUE TITLE
Health and aggro not updating

### ISSUE THREAD

**Issue by Zwyk** [Luxocracy/NeatPlates#306]
Hello,

I'm having an issue with the health and aggro indicators not updating until I either mouseover or target the mobs. Other things are probably not updating but that's what I could see.

Here is a short video of it happening : https://i.imgur.com/grhzfRb.mp4

**Comment by Luxocracy** [comment]
There's an option in the main settings to _Force Health Updates_, which should help. But as far as I've been able to tell this is an issue with the servers not reporting health updates correctly. Because normally the server would announce that x mobs health has changed. Which is a lot more efficient performance wise, but this option will check every so often if the mobs health has changed instead.

**Comment by Zwyk** [comment]
Oh alright thanks! It's much better like that :)
