### ISSUE TITLE
Curse of the Elements

### ISSUE THREAD

**Issue by haroldinerince** [Luxocracy/NeatPlates#310]
On my warlock Curse of the Elements no longer seems to display as a debuff on my plates?

Everything else seems perfect. Is this a known issue?

**Comment by Luxocracy** [comment]
I've seen someone else mention it, but I don't know if what I suggested actually helped.

Assuming you are using the default _only my auras_ filter mode, you could try adding it as an additional aura and setting the filter for it to anyones. As I'm assuming the game isn't registering it as your curse a with other auras do. Probably due to it being a unique debuff or something.

**Comment by haroldinerince** [comment]
Added it by name under Additional Auras and it works fine like that again!

Thanks :)
