### ISSUE TITLE
Issue with aura widget additional aura filter

### ISSUE THREAD

**Issue by Golrathcr** [Luxocracy/NeatPlates#314]
There has been a long standing issue with the additional aura filter for me ever since it was reworked.  I mostly white list auras that I want to be able to see and have a long list of 100+ buffs on the filter. Whenever I try to add new auras to the filter, the entire list often becomes invisible and unreadable, but the spells are still there in the list because I can still mouseover them and the list returns when I reloadui. The UI itself also seems to often get very choppy/laggy when interesting with the list of auras, often freezing the game for several seconds. This issue did not exist with the previous aura widget and only began happening after the rework a while back.

**Comment by Luxocracy** [comment]
I mean the previous aura widget was nothing more than a text box, there's not a lot that can go wrong compared to the current design. So I guess that is an upside to the older design.

I've looked into the lag a bit before but I couldn't determine what the cause for it was. I'm assuming there's some hook that doesn't get overwritten/unhooked properly causing it to trigger once for each interaction that causes the list to update. I'm gonna take another look and see if I can manage to find the issue.

As for the issue with the list items becoming invisible, it's something I've never experienced so if you have a method of reproducing that issue I'd be grateful. But it's very likely caused by the same issue that is causing the lag, so it might not be necessary.

**Comment by Luxocracy** [comment]
I managed to find the issue, it was indeed a frame that wasn't being re-used. Causing new ones to be created whenever the list needed to be updated.

So if you have over a 100 list items, it would quickly get out of hand with the amount of frames just lingering.

**Comment by Golrathcr** [comment]
This works correctly now, thanks for the quick fix/reply. Greatly appreciated. Sorry for the late reply.
