### ISSUE TITLE
Health bar values and aggro state on nameplate not updating until mouseovered 

### ISSUE THREAD

**Issue by Jazo420** [Luxocracy/NeatPlates#315]
I've noticed since TBC came out that health bar values and aggro state are not updating in real time when I am not currently targeting that mob.

For example, I would be targeting our tank and healing him while they are fighting a pack of 5 mobs, to me those mobs look like they have full HP the whole time, until I mouseover their nameplates then they immediately update to their current health value.
It also happens as a dps when im not targeting a specific mob it just wont update their health values until I mouseover it.

I couldn't find a clear example but I do have these 2 clips showing what I mean:

https://user-images.githubusercontent.com/45575075/126791173-5b096c76-7ed1-4bbe-a46c-eabb118a00e5.mp4

https://user-images.githubusercontent.com/45575075/126791181-76e93079-93ba-41b7-9aa0-337d9e7f1c70.mp4

It also doesn't update the aggro state until you mouseover it sometimes (where you have an aggro on a mob but it doesnt show that you do until you mouseover it): 

https://user-images.githubusercontent.com/45575075/126791197-a584ba15-1d09-4653-896e-2315c91253f6.mp4

(I had aggro on the small add the whole time but it didn't show until I mouseovered it.

I hope this was clear enough to show what I mean.
I am not sure if its neatplates doing this or is it interfering with another addon and causing it to do this, I hope you can find a solution though.

**Comment by Luxocracy** [comment]
Try enabling the _Force Health Updates_ option found in the main settings. This seems to be an issue with the TBC client itself, hopefully it gets resolved and the workaround found in the main settings won't be needed for some people.

**Comment by Jazo420** [comment]
Seems to be fixed with that, thank you!

**Comment by ars4l4n** [comment]
I was having a similar issue too, even 1 year later (just that the health values don't update when I mouseover a mob. In my case, they update regularly but seem to lag behind substancially.) I've checked "Force Health Updates" and it works fine for me now, too. Perhaps it should be the default setting for TBC clients because I can imagine many users like myself getting overwhelmed and frustrated with having to troubleshoot it themselves when they just want to play WoW and have fun
