### ISSUE TITLE
Emphasized auras issue.

### ISSUE THREAD

**Issue by Golrathcr** [Luxocracy/NeatPlates#318]
When the amount of emphasized auras is set to 3, the addon is still limited to displaying 2 emphasized auras at a time. I have tried multiple different sizes/settings for the emphasized auras and I cannot get it to display 3 when set.

Also when this limit of 2 is reached, any further emphasized auras that need to be displayed do not automatically show as normal auras unless you create both an emphasized and normal aura for it. 

This means you need to create 2 auras for every emphasized aura if you still want it to show on the nameplate once 2 emphasized auras are already displaying.

**Comment by Luxocracy** [comment]
There's an option to display the normal aura as well as the emphasized, I believe it's at the bottom of the Buffs & Debuffs section. Although this could possibly be moved to the aura itself so that this can be controlled on an individual basis.

I'll have to look into the issue with only 2 emphasized auras being displayed, even if the option is set to 3. And also look into what should happen to an aura if it can't fit into the emphasized auras. I think there should be something in place for if that happens already, but I could be remembering wrong.

**Comment by Golrathcr** [comment]
The option to display the normal as well as emphasized shows both at the same time. The scenario I was trying to point out is one where you don't want both the normal and emphasized auras showing simultaneously, but the maximum emphasized auras are showing.

In that scenario the other auras that are emphasized will just not display because there already 2 emphasized auras showing. So the aura will just not display at all unless you also add second copy of the aura as a normal aura. It would be nice if they could show as a normal aura if they is no room to be displayed as an emphasized aura, or if there was a way to make more emphasized auras able to be displayed.

**Comment by Luxocracy** [comment]
After looking through the code, everything you describe is how it's intended to work. However, I found 2 separate issues that prevented this from happening in certain cases.

- If your normal auras are showing less than 4 auras per row(aka aura scale set to more than 98%) the Emphasized aura slots would get set to 2 due to an oversight.
- If the aura shouldn't have been displayed normally, through the general aura filters, it wouldn't overflow back into normal auras if the emphasized slots were full.

Both these things are fixed in the latest release and all the issues you've mentioned should be resolved.

**Comment by Golrathcr** [comment]
Just tested the new version, both scenarios are now working correctly. Thanks again, appreciate the quick responses/fixes.
