### ISSUE TITLE
Not able to see lvl/skull icon on elite units using the Blizzard theme

### ISSUE THREAD

**Issue by Siffran** [Luxocracy/NeatPlates#323]
![image](https://user-images.githubusercontent.com/22680366/134009737-8b2bae5a-45e0-42af-b8e3-6eaed36e931a.png)

![image](https://user-images.githubusercontent.com/22680366/134009875-add1311c-9f32-4fb3-bc8e-526f1f7f15f9.png)

![image](https://user-images.githubusercontent.com/22680366/134009921-b25f69a0-39ae-4a12-9197-94a5820cf7e1.png)

**Comment by Siffran** [comment]
Seems to work with target dummies, maybe this was an isolated issue with the mobs I found?

![image](https://user-images.githubusercontent.com/22680366/134044683-c705ccc1-67fb-4924-b1f3-10a200da0331.png)

**Comment by Luxocracy** [comment]
Hey, sorry for the late response.

I looked into this and found that the function that checks if the skull icon should be displayed was using the older _UnitLevel_ function, that retrieves the unscaled level of a unit. Instead of the relatively newer _UnitEffectiveLevel_ which the level function uses. Basically the scaled version that fetches unit level was saying this is a skull unit, but the older one was retrieving an actual level.

This should be fixed in the latest release.
