### ISSUE TITLE
Version 1.14

### ISSUE THREAD

**Issue by Casualpop** [Luxocracy/NeatPlates#324]
Will you by any chance release an updated version of your addon for classic version 1.14. Current one not working. thanks.

**Comment by Luxocracy** [comment]
I took a quick look at it and made a alpha version with the TBC/Retail version as a base, because essentially they are the same clients now with the era update. And this works for the most part.
However, it seems like certain things like castbars and debuff timers do not work with that version. As they rely on either third party libraries or features that aren't necessary in TBC/Retail.

So I would assume that they still, for some reason, won't add these into the Classic era version of the game. And that leaves me with two choices if I were to create a proper release for it.

Either, re-add the classic features into the current TBC/Retail version. Which would be the preferable method as it makes it a lot easier to maintain the addon. But since there are a lot of Classic only quirks, and having to rely on third party libraries, it also increases the difficulty of maintaining the addon.
Or, fix the current Classic version so that it works with the Classic era client. Which would probably mean that that version wouldn't be getting any new features or re-works that may happen in the future. And will probably only be updated if something breaks it. Pretty much it's current state.

Sorry if I started rambling a bit there, just wanted to write out my thoughts to outline my thought process.

But I think in general it will depend on how much interest there is around a Classic version of the addon, as well as if the third party libraries that the Classic version relied upon gets updated for the Classic Era client. So I can't really give a definitive answer as to if I'll update the addon for Classic era.

**Comment by Teknishun7** [comment]
First of all thanks a lot for doing this :)

As you already know NeatPlates broke as soon as Blizz updated the API. Nameplates were invisible from 0 to 20 yards then names became visible from 20 yard up and the Nameplates config panels were gone completely even /NeatPlates wouldn't show them.

I tested what Kaivax (Community Manager) from the recent blue post on the warcraft forums suggested and tried out the TBC version in Classic Era. It kinda worked. I could now see the NamePlates again from 0 to 20 yards, but the config panel was still not available even with the /NeatPlates command.

I tried out your latest update 1.14.0.1-alpha and the NamePlates became invisible again, but part of the config panel came back. I can't configure much it's only the theme window with the general options the second panel with the in-depths options still missing. I also cleared all my Cache/Interface/WTF Folders to test again and same results happened.

Thanks again. Seriously.

**Comment by Teknishun7** [comment]
Hey, just wanted to give a quick feedback after a second test,

I decided to wipe my game completely and retry installing from fresh. I also redownloaded the Addon to make sure my first download wasn't corrupted or something.

I don't know what changed, but its working great now. I haven't tested out more than walking around a city, but NeatPlates seemed to work just like before 1.14, I could even successfully reimport my old settings, so I guess the issue was on my end.

A big thanks for updating you have no idea how grateful I am. :D

-Fluxie from Ashkandi Classic Era.

**Comment by Casualpop** [comment]
> Hey, just wanted to give a quick feedback after a second test,
> 
> I decided to wipe my game completely and retry installing from fresh. I also redownloaded the Addon to make sure my first download wasn't corrupted or something.
> 
> I don't know what changed, but its working great now. I haven't tested out more than walking around a city, but NeatPlates seemed to work just like before 1.14, I could even successfully reimport my old settings, so I guess the issue was on my end.
> 
> A big thanks for updating you have no idea how grateful I am. :D
> 
> -Fluxie from Ashkandi Classic Era.

What version of the addon are you using?

**Comment by Teknishun7** [comment]
Version that just came out 1.14.0.1-alpha. It's working fine for me now. I dont know why first time I tried I had issues, but I retried it from fresh and it worked. Been testing it for 3hrs+ now and it's working just like it used to in Classic 1.13

**Comment by Teknishun7** [comment]
Version 1.14.0.1-alpha. Its working fine, but some features are missing. Better than no nameplates. I can give a last feedback later on features that arent working, but so far it's at least usable.

**Comment by Teknishun7** [comment]
Basically what Luxocracy said is a good resume of my issues. Overall its working, but some features aren't.

**Comment by gccmbr** [comment]
With Fresh Classic Season of Mastery Beta starting Oct 5 (Tuesday), I also booted up to get ready and installed the Alpha 1.14.  I will report back my findings over the next few days.  Thanks for everything!  Everyone get excited for new launch!

**Comment by zdeyn** [comment]
With regards to aura/buff/debuff durations, LibClassicDurations seems to be almost plug-and-play. I recently hacked out a hybrid Classic/TBC version of ElvUI for personal use, and switching back from TBC's auras to using LibClassicDurations was only 10 or so lines of code (which I just grabbed from the prior Classic version of ElvUI, so I'm not an expert by any means)

I guess what I'm saying here is: a version check to switch between native and 3rd-party stuff doesn't have to be a big deal.. and with Fresh coming, the userbase will only increase!

As it is, there's a bunch of people playing 'Hardcore' mode on Classic Era that have been asking me to help get various addons working, simply because I'm willing to give it a try :) Having an author-supported solution would be wonderful!

Happy to supply what I did to some other addons, if that'll help you get things up and running again

**Comment by zdeyn** [comment]
Not sure about 'supported' by the authors, but it definitely still works :)

If you need a hand, let me know

**Comment by Luxocracy** [comment]
I've released a new version that should have working aura timers as well as castbars. I only tested it briefly but it seems to work properly.

There are probably still some issues with it, and I haven't look at what features are missing or doesn't work, but hopefully they are minimal.

**Comment by Teknishun7** [comment]
Thanks so much! I will test the new version as soon as I get home!

**Comment by Teknishun7** [comment]
Can confirm 1.14.0.2 alpha should work great on anyone's Classic Era Client. Tested it for about 30 mins with my guild and all the features were working A1 to my knowledge.
ThreatMeter, Castbars and Auras are all working.

Didn't get a chance to test your "v408" which looks like an Universal version if I understood correctly.

Thanks for the Update !

**Comment by Luxocracy** [comment]
The newer versions like "v408" should be identical in functionality the 1.14.0.2 version, as I opted for a universal solution from the start. The only difference is that it implements multiple .toc files to allow for a single release to work across multiple clients, as noted [here](https://github.com/Stanzilla/WoWUIBugs/issues/68#issuecomment-830351390).

**Comment by Casualpop** [comment]
Its working like a charm now, thanks a bunch for this :)
