### ISSUE TITLE
Non-target Alpha "opacity" when set to max and you target anything "all non-targets drop to half opacity"

### ISSUE THREAD

**Issue by octamooze** [Luxocracy/NeatPlates#329]
**What version of the game you are experiencing the issue with:**

                       TBC 

**Describe the bug**

the non-target alpha opacity setting, when set to max the targets are still only half the opacity. and or there is just not a setting where you can turn all bars to be fully active. with this being said. as soon as you target someone, the setting for occluded alpha multiplyer become usless because all non target bars instantly become faded. 

**To Reproduce**

this addon seems to be working correctly, but 1 setting

**Expected behavior**
 
i expect to be able to trun the non-target alpha opacity setting to max and all bars become luminated to max all the time. there for i will be able to use the occluded alpha multiplyer setting for "line of sight".

**Comment by Luxocracy** [comment]
There's 2 settings that control the opacity/alpha of the nameplates.

- In the main settings under the _CVars_ section called _Non-target Alpha_
- In the profile settings under the _Opacity_ section called _Non-Target Opacity_

I know it's a bit counter intuitive, but it's because the way the _Occluded Alpha_ is implemented that is has to be done this way. So as to not lose out on previous functionality in the profiles _Opacity_ settings.

**Comment by octamooze** [comment]
ok you are awesome,
