### ISSUE TITLE
Nameplates overlapping friendly, stacking enemy

### ISSUE THREAD

**Issue by aurorascharff** [Luxocracy/NeatPlates#332]
**Is your feature request related to a problem? Please describe.**
I use the console command /run SetCVar('nameplateShowOnlyNames', 1) like many other raiders. This allows me to turn on friendly nameplates and see everyone's names clearly. However, I do not want the friendly nameplates to stack, because then they will take up too make space. I do however want the enemy nameplates to stack because then I can see them all. Plater has implemented something to solve this - an option that makes only the enemy nameplates stack and keeps the friendly ones overlapping. It would be incredible if neatplates could do the same!

**Describe the solution you'd like**
An option to allow enemy nameplates to stack, while friendly ones overlap.

**Describe alternatives you've considered**
- Installing plater
- Using overlapping plates in raid and not seeing all enemy frames (works because I'm a healer but still not optimal)

**Comment by Luxocracy** [comment]
I'll take a look and see what can be done. My assumption is that plater basically just implemented this command. Which makes nameplates basically take up no space.
`/run C_NamePlate.SetNamePlateFriendlySize(1, 1)`

This doesn't currently work with neatplates properly as this will get overwritten on load. I had someone ask if I could fix this, but I couldn't find the reasons behind running this command. And they never got back to me.

But this makes perfect sense to be used for what you described.

**Comment by aurorascharff** [comment]
Perfect! Thanks for getting on this so quickly.

**Comment by aurorascharff** [comment]
Thank you so much, truly! Working perfectly.

**Comment by aurorascharff** [comment]
Think I found a bug: I turned it on and it was working in a dungeon, however, it suddenly stopped working and some of the plates also turned to a lower opacity randomly. Clicked the option off and on- working again.

**Comment by Luxocracy** [comment]
The opacity changing sounds quite odd, not really sure what that would be about.

As for it breaking in the dungeon, I'll have to double check so I missed something that would cause it to revert the option.
It's also possible that something else changed it, like another addon or something built in by Blizzard, as it is basically just a console command.

**Comment by aurorascharff** [comment]
Yeah. Could be anything. Been working reliably since then!

**Comment by aurorascharff** [comment]
![image](https://user-images.githubusercontent.com/66901228/160245645-16083bce-bc09-4c78-8678-e54c3c7fc02a.png)
Got this bug when it stopped working randomly today

**Comment by Luxocracy** [comment]
Hmm, if the issue is caused by a taint to the unitframes it could literally be any addons doing.

Finding out if the cause is Neatplates can be a bit tricky but if your willing to help me out, we might be able to find out.

Basically, I would need you to enable the taint log by running this command `/console taintLog 1`
And then once the error occurs do a `/reload` and look in your logs folder `Battle.net\World of Warcraft\_retail_\Logs` for a `taint.log` file. 
If you can then send that file to me I take a look to figure out what is causing the frame to become tainted.

It's a bit of a hassle but it'd be really helpful.

**Comment by aurorascharff** [comment]
[taint.log](https://github.com/Luxocracy/NeatPlates/files/8356389/taint.log)

**Comment by Luxocracy** [comment]
Judging from the log there are 2 addons causing taints, which are preventing certain actions.

**FriendGroups** & **RCLootCouncil**

Looks like **FriendGroups** was updated yesterday, so the issue might have been fixed with the update.

As for **RCLootCouncil**, I think it's taint issues have been around for quite som time, but generally not causing issues.

So my bet would be on **FriendGroups** being the issue, at least as far as it being the reason for the error message.

**Comment by aurorascharff** [comment]
Thanks for looking into it, I'll disable the addon(s) and see whether it stops the issue from happening again!
