### ISSUE TITLE
Health Bar Delay since new TBC Phase 4 Patch

### ISSUE THREAD

**Issue by Sn4ppyDr3w** [Luxocracy/NeatPlates#333]
Hi, I'm not sure if I'm the only one experiencing this, but wanted to bring it to attention at least.  I've noticed the health bars on the nameplates while farming random mobs is delayed quite a bit.  It even says the mob is still full health sometimes as I'm casting my 3rd or 4th spell to kill it.  I've only noticed this with mobs out in the open world, as during raids it's seemed to work just fine, as before.  This just started happening after the most recent big patch for Phase 4.  Thanks for any help you might have for this issue!

This is using the current version of TBC Classic.

**Comment by Luxocracy** [comment]
This sounds very similar to an issue in Classic that was around for a while. As far as I could tell at the time was that the server didn't report health updates correctly.
And I believe this issue went away entirely on its own after a while.

But the workaround for it still exists in the main settings called **Force Healthupdates**. You could try and see if that resolves your issue.

**Comment by Sn4ppyDr3w** [comment]
Thanks so much for the help!

**Comment by samwow412** [comment]
also experiencing this, ive noticed it happens in raids too prior to the 2.4 patch, esp on AOE packs

**Comment by crx-au** [comment]
I've also been experiencing this in the last month or so, and enabling "Force Health Updates" as suggested has worked! Thanks for leaving the workaround in place :)

**Comment by Luxocracy** [comment]
Just an update on this incase someone stumbles on this while looking for a solution.

I've rewritten the way health updates are done to mirror the way it's done by the default blizzard nameplates. But I've still seen reports of this being an issue for some people in TBC. Which further strengths my beliefs that it is a server issue.

What I might do is inverse the option regarding "forced health updates" for TBC specifically so that it becomes an opt-out feature instead of opt-in.

Why even include the choice you might ask? Ultimately the forced health updates can lead to a loss in performance. And while Neatplates isn't the most performant addon, most of the features that lead to a loss in performance are opt-in. Which is how I believe such things should be.

On a side note, I should probably include in the tooltips how much impact a feature can have on performance. So that the users can be properly informed about them.
