### ISSUE TITLE
Can't move castbar under Theme Customization

### ISSUE THREAD

**Issue by chon379** [Luxocracy/NeatPlates#341]
I am trying to center the castbar under the healthbar, as its currently offset to right a little bit. However changing the X and Y settings do nothing to the castbar at all.

**Comment by Luxocracy** [comment]
Hi, sorry for the delay in response. I just completely missed the notification for this.

The castbar situation is a bit weird right now for theme customization. Well theme customization in general is in a bit of a weird place. It currently has, I believe, 7 parts that need to be moved individually. So this might be why it doesn't seem to move for you.

Also make sure you've selected the correct **Style Mode** and **Profile**, so that you aren't trying to move something that isn't being used/displayed in your current setup.

Here are the items that would potentially have to be moved, depends a bit on what settings you have enabled.
- Castborder (non-interruptible)
- Spell Icon
- Castbar
- Castbar Spell text
- Castbar Spell Target
- Duration/Cast time Text
- Castbar Border
