### ISSUE TITLE
NeatPlates Configuration error, explain in detail

### ISSUE THREAD

**Issue by s890214** [Luxocracy/NeatPlates#357]
**What version of the game you are experiencing the issue with:**
WLK

**Describe the bug**
the hostile >>> player options not work，and  friendly >>> player options  work to hostile

**To Reproduce**
me ：Aalliance
target：Horde

uncheck or check   the  friendly >>> player options

shift+v open，
![微信图片_20221018110044](https://user-images.githubusercontent.com/29193110/196326423-bce7989d-456a-4d4e-931b-f4baa80cfb19.png)

shift+v open
![微信图片_20221018110050](https://user-images.githubusercontent.com/29193110/196326439-2b4e64f4-0826-4f0d-bdfd-d5e13444f4b2.png)

shift+v close
![微信图片_20221018110053](https://user-images.githubusercontent.com/29193110/196326446-cbff0168-59ab-4776-84f1-9a7b033d52d3.png)

shift+v close
![微信图片_20221018110056](https://user-images.githubusercontent.com/29193110/196326458-a0802e39-11d5-4330-a886-42dd4fcba314.png)

shift+v close
![微信图片_20221018110059](https://user-images.githubusercontent.com/29193110/196326463-27cfccf4-d9f6-4112-b542-0fe302fa7399.png)

**Comment by Luxocracy** [comment]
Sorry that I've not responded to this in a while.

I think I figured out what is going on, and it's entirely related to the fact that you are in a neutral city. Where Neatplates does not consider the opposite faction to be an enemy. Which is how it's been for a very long time.

However, since the normal nameplate settings relating to **Friendly/Enemy Nameplates** do still apply even in neutral cities. It would only make sense that Neatplates does the same. So I am looking into changing this behaviour, but issues affecting retail are currently taking priority.
