### ISSUE TITLE
Update needed for rogue combo points

### ISSUE THREAD

**Issue by Shadowmastr** [Luxocracy/NeatPlates#360]
Along with the addon just not allowing you to use your keyboard, there will most likely need to be an update to rogue combo points. They are not currently displaying at all with the new patch.

With the new talent system, rogues can select a choice between 5, 6, and 7 possible combo points (with the different talent options) between the 3 specs.

All 3 specs can get up to 6 combo points by selecting Deeper Stratagem in the class tree (https://www.wowhead.com/beta/spell=193531/deeper-stratagem).

Outlaw can add 1 additional combo point in the outlaw specific tree from Devious Stratagem (https://www.wowhead.com/beta/spell=394321/devious-stratagem) creating the option to have 5, 6, or 7 combo points depending on talent selections.

Sub can also add 1 additional combo point in the sub specific tree from Secret Stratagem (https://www.wowhead.com/beta/spell=394320/secret-stratagem) creating the option to have 5, 6, or 7 combo points depending on talent selections.

Assassination can only select additional combo points from Deeper Stratagem in the class tree, so you can only have a choice between 5 or 6 combo points.

Hope this helps!

**Comment by Luxocracy** [comment]
Hi,

The new dragonflight version has a completely redesigned personal resource widget(combo point widget). This new widget should work with this change as it now dynamically creates it based on your max combo points rather than using fixed values.

I've marked it as a beta feature right now as I would like to add some more styles to it. Like for example the default combo point look is currently not available in it, which is something I'd like to add. As well as it requiring some more testing.

And just as a note, I don't have any plans of updating the older widget to work with the new 7 combo points. Unless there is some major issue with the new widget.

**Comment by Shadowmastr** [comment]
Thanks for the response! 

One other thing: are there any plans to have the combo points display with the original color scheme? It looked something like this:
![cpcolors](https://user-images.githubusercontent.com/72906585/199153945-db71bec9-e5fd-4a52-92a5-b1f14058a262.PNG)

Now, the combo points are just one generic red color:
![cpcolornow](https://user-images.githubusercontent.com/72906585/199154026-8b9bb4cf-259d-4d4c-9c26-82cecdc5e505.jpg)
