### ISSUE TITLE
Please add NeatPlatesTraditional style in Personal Resource Display(BETA) section

### ISSUE THREAD

**Issue by gazette2** [Luxocracy/NeatPlates#373]
**What version of the game you are experiencing the issue with:**
Live/Retail

**Describe the bug**
Could you implement NeatPlatesTraditional style in the new Personal Resource Display(Beta) section? I prefer old style Resource widget to new one. I'm currently off the new resource display widget and using old one but there are bugs in the old resource widget.

1. Rogues now can have 7 combo points
2. old resource widget makes problem with warlock specs

**To Reproduce**
Rogue
1. In Outlaw rogue talents, select 'Deeper Stratagem' and 'Devious Stratagem'
2. Off the new Personal Resource Display by selecting 'Show on: None'
=> Combo Points are invisible.

Warlock
2. Off the new Personal Resource Display by selecting 'Show on: None'
=> DeBuffs & Combo Points are invisible.

**Comment by Luxocracy** [comment]
Sorry for taking a while to respond.

The new resource widget will be getting the _gradiant_ styling, yellow to red, for combo points in the future, hopefully very shortly. However I currently have no plans on adding the version that has black borders, but I could probably be swayed to do so if that is the specific one you really want.

As for the old widget, I've fixed the issue Warlocks in the latest release. However I will not be adding support for 7 combo points due to the tediousness of doing so. A major part as to why its been re-written.

When setting the **Show On** to **None,** it should indeed be hidden. It controls on what unit type it should be displayed. So this is correct behaviour.
What was the behaviour you were expecting of it?

**Comment by gazette2** [comment]
Thank you for your kind reply. 

I was originally a TidyPlates user, and I moved on to NeatPlates when it didn't update for a while. When TidyPlates started updating again I was able to move on to TidyPlates again, but I didn't because NeatPlates side was functionally better. However, I liked the Neon style artwork of TidyPlates very much. I wanted to apply that style to current version of NeatPlates, and that's why I made a request.

Currently, I wrote a personal version that made some modifications to the graphic files and made it look as similar as possible. Thank you again for your great addon.
