### ISSUE TITLE
Gold Dragon Elite Icon not showing up for certain mobs like Bastion Training Dummies and Lord Kazzak when show Elite Icon is checked

### ISSUE THREAD

**Issue by Spkilla** [Luxocracy/NeatPlates#381]
**What version of the game you are experiencing the issue with:**
Live/Retail

**Describe the bug**
Gold Dragon Elite Icon not showing up for certain mobs like Bastion Training Dummies and Lord Kazzak when show Elite Icon is checked. it is not all elites, as the prepatch elementals have the elite dragon border. other mobs i found is Lord Kazzak is also missing

**To Reproduce**
1. Go to 'Interface'
2. Click on 'Neat Plates'
3. Choose Profile/Default
4. Scroll down to 'Other Widgets.'
5. Check Show Elite Icon
6. Go to Bastion Training dummies, or Lord kazzak in blasted lands for anniversary no gold dragon elite on name plates

**Expected behavior**
Gold Dragon Elite Icon around level on floating nameplates when "Show Elite Icon" is checked or selected for all elite mobs

**Screenshots**
![WoWScrnShot_111822_120304](https://user-images.githubusercontent.com/38851009/202760959-0f1ad70f-4625-4162-80bf-194af8c1e07b.jpg)
![WoWScrnShot_111822_120813](https://user-images.githubusercontent.com/38851009/202761914-21952771-50c2-4890-900a-0efc33ad1f78.jpg)

i loaded up tidyplates to show what it should be
![WoWScrnShot_111822_121346asdsadsad](https://user-images.githubusercontent.com/38851009/202763184-2c7c29dc-9af5-457e-8529-e63849b7a081.jpg)
![WoWScrnShot_111822_121352](https://user-images.githubusercontent.com/38851009/202763469-327d25bf-f62a-4225-8e55-8e20f3aa9b3b.jpg)

though tidyplates is also a little broken as the Stalwart Guardian is also elite but its missing as well
![WoWScrnShot_111822_121346](https://user-images.githubusercontent.com/38851009/202763365-ee6e232d-7f2c-4c10-99fb-1141e7c344c5.jpg)

![WoWScrnShot_111822_121043](https://user-images.githubusercontent.com/38851009/202762341-fb8af254-9a7c-4c18-9f96-dbffa0b09f1c.jpg)
![WoWScrnShot_111822_121004](https://user-images.githubusercontent.com/38851009/202762231-1ee45b21-d5b1-41a7-aecf-2c1c0e241e31.jpg)
**Additional context**

**Comment by Luxocracy** [comment]
Sorry for taking a while to respond to this.

But is still an issue? Because I am not able to reproduce it on retail. This option works as intended for me.

Have you made any changes in the **Theme Customization** found at the bottom of your profile settings? As this can also be hidden by selecting _Elite Icon/Border_ and unchecking the **Element Enabled** checkbox.

**Comment by Xavyrr** [comment]
Hello. It looks like this is still an issue. I just tested with the training dummies in the Ebon Hold (the elite one in the center doesn't have an elite marker.) I even made some absurd changes to the lua config file to make it really big. Seems to be with just some enemies. Thank you for you hard work!

**Comment by Luxocracy** [comment]
Not sure how I missed it last time I looked at this, but this is for boss enemies. And boss enemies have intentionally had their elite icon hidden since the start.

But I've added an option for the next release that lets you display it for boss enemies as well if that is something you want. It can be found just underneath the "Show Eliteicon" option.
