### ISSUE TITLE
Healthbars issue

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#39]
Sometime, The percentage of the healthbar doesn't synchronize with the target frame’s.
Like the following picture:
![tim 20181112190746](https://user-images.githubusercontent.com/44251440/48344227-62706b00-e6af-11e8-910b-5ba55b9bb692.png)

**Comment by Luxocracy** [comment]
I've never seen my healthbar be out of sync, nor can I seem to recreate this happening when trying. So I would need some more context on how to replicate this issue.

Secondly, could you check if it's just the graphic being out of sync or the entire plate by changing "Enemy Status Text" to "Health Total & Percent" and see if those values are out of sync as well?

**Comment by yishuangfrank** [comment]
This issue has existed for a long time.
 “Dragon Soul”，the 7th boss “DeathWing“，”Hideous Amalgamation“
When it get 9 buff and kill it.

**Comment by Luxocracy** [comment]
The only way I've been able to replicate something similar to this issue is by removing the event handler for "UNIT_HEALTH_FREQUENT". Which leads me to believe this is caused by either the server not sending the event, or the UnitID provided by this function is sometimes incorrect.

I've switched the event from "UNIT_HEALTH_FREQUENT" to just "UNIT_HEALTH" in [this test version](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.12a-debug), hopefully that makes it better because otherwise I have actually no clue as to what is possibly causing this issue, since I can't replicate it at all.

**Comment by yishuangfrank** [comment]
Thanks.
It' night in China, I'll try it tomorrow.

**Comment by yishuangfrank** [comment]
This version works better.
I will test it more.

**Comment by Luxocracy** [comment]
No, only that specific version does.

The test/debug version uses a method that gets throttled when under load while the normal version uses one that shouldn't get throttled. But if this version is performing better, then I'm assuming there is something going on with certain regions/realms and the un-throttled version of that method. And using both would, in most cases, cause a large amount of unnecessary updates to the healthbar which I would want to avoid if possible.

I will test a few things and see if I can come up with a middle ground that I am happy with.

**Comment by yishuangfrank** [comment]
OK. Thanks a lot.

**Comment by Luxocracy** [comment]
In the latest [pre-release(pre5)](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.13-pre). There is now a setting for using frequent health updates or not, defaults to enabled, in the main settings menu.

**Comment by yishuangfrank** [comment]
Great！

**Comment by yishuangfrank** [comment]
I can't un-check “Use Frequent Health Updates” in pre-release(pre5).

**Comment by Luxocracy** [comment]
Seems I overlooked something. I've added another version(pre6), it should now work properly.
