### ISSUE TITLE
Purgeable buffs not showing in SOD

### ISSUE THREAD

**Issue by Dropehx** [Luxocracy/NeatPlates#411]
In WoW Classic SOD Purgeable buffs are not showing in enemy nameplates. This is despite having the "Include purgeable buffs" option marked and "Show all" in the buff filter option.

**Comment by Luxocracy** [comment]
Sorry for the late reply on this.

For Classic you can't generally see buffs unless you have something like "Detect Magic" applied to the enemy. So this is sadly a limitation imposed by the Classic version of the game.

But if a buff is applied while you are in the vicinity of, that is if it gets registered in the combat log, it should also show up on the nameplates thanks to a library called [ClassicDurations](https://github.com/rgd87/LibClassicDurations). Although I have no idea if this is still being maintained, so it might be an issue with this.

Could you confirm that this issue is happening when an enemy applies a buff right in front of you?
