### ISSUE TITLE
Not working properly on some alts

### ISSUE THREAD

**Issue by Connordan** [Luxocracy/NeatPlates#418]
**What version of the game you are experiencing the issue with:**
Cata classic

**Describe the bug**
When I log onto an alt, it seems like NeatPlates is not overriding all of the default nameplate settings. NeatPlates won't keep the nameplate on the screen at all times, regardless of if it is checked in the settings or not. The namplates of enemies not targeted will also get more opaque similarly to how it would if you did not have neat plates, even though It won't do that on my main character. I verified I have the correct profile selected. 

**To Reproduce**
I would only suggest seeing if it works on different alts. 

**Expected behavior**
See bug description

**Screenshots**
![image](https://github.com/Luxocracy/NeatPlates/assets/172303145/7bb2fdcc-a055-4e25-b30a-c9d836cdeb29)
![image](https://github.com/Luxocracy/NeatPlates/assets/172303145/63c5f3bd-a126-4065-8521-68988c7a095e)

the first is my main, non targets are always set to 85%
second is alt, the get even more opaque when I target a mob

**Additional context**

**Comment by Connordan** [comment]
![image](https://github.com/Luxocracy/NeatPlates/assets/172303145/3e92fc8c-4904-410b-b15b-1d8de2c4aa75)
![image](https://github.com/Luxocracy/NeatPlates/assets/172303145/ef86f9d7-f0bd-430d-92e8-21c25c020a84)

You can also see how on the alt the nameplate won't stay on the screen, but on the main it does

**Comment by Connordan** [comment]
So far the only thing I can tell that is different between the 2 characters it works on and the others is that does not is the characters it is not working on are not max level. Unsure if that is random.

**Comment by Connordan** [comment]
![image](https://github.com/Luxocracy/NeatPlates/assets/172303145/e65d4486-d96d-46c2-91fb-0ae9a4d35481)
Another thing I noticed, some friendly players have the default blizzard names which is what I want, and some have different looking names which I assume is something the addon can do?

**Comment by Luxocracy** [comment]
Sorry for the late response on this.

This is most likely related to when the characters were created. Blizzard occasionally changes what the "default" nameplate settings are or have hidden certain options from the games interface menu.

I don't recall exactly what can cause the issue you described. But assuming the "Keep target nameplate on screen" option is checked in the main Neatplates settings are the CVars named something like "nameplate_____Inset". The opacity issue I believe is also caused by one of the "nameplate_____alpha" CVars. Sorry that I can be of more help here.

The "different looking" nameplates are the "Headline View" or "Text-Only" version of the nameplates, these generally show up in place of the nameplate healthbars and are controlled under the "Nameplate Style" section of the profile settings.

The default blizzard names can only be displayed if a nameplates are toggled off. Either through the default blizzard options, or through the "Automation" section of the main settings.
