### ISSUE TITLE
Profiles cant be deleted / And a question

### ISSUE THREAD

**Issue by Rinkashirukito** [Luxocracy/NeatPlates#425]
**What version of the game you are experiencing the issue with:**
Live/Retail

**Describe the bug**
Profiles cant be deleted. Pressing Yes when trying to delete a profile just doesnt do anything, it doesnt close the dialog, it doesnt pop any errors, the button flat out does nothing.

**To Reproduce**
Try to delete a profile -> Click Yes when asked to delete -> nothing happens

**Expected behavior**
I expect the profile to be deleted :D

**Additional context**
In addition to the bug reported, i have  a question about some settings. Why are there 2 personal resource setting? One is under the personal resource (beta) and one is under the other widgets. The one under personal resource beta controls my combopoints/essence/runes etc, but the one under other widgets seems to do nothing?!

**Comment by Luxocracy** [comment]
Deletion of profiles should now work again in the latest release.

As for the personal resources.
The **Beta** one is a complete rewrite of the function that allows the addon to be a bit more flexible when changes to a classes personal resource occurs from gameplay changes etc. The old one can only be accessed/used if the new beta one is set to **None**. 

And basically the reason I sort of had to release it as a beta was due to the previous expansion release that broke the old one for rogues in particular. And there being no support for the Evoker in the old one. It's still in beta because I still intend to, at some point, implement the old themes in the new version.

**Comment by Rinkashirukito** [comment]
Thank you for the response! Makes sense that nothing changed when i tried to use the old one cause i had the beta one enabled ^^
