### ISSUE TITLE
Issues with spell interrupts and channeled spells

### ISSUE THREAD

**Issue by Ainlaen** [Luxocracy/NeatPlates#433]
**What version of the game you are experiencing the issue with:**
Classic SoD

**Describe the bug**
1. Channeled spells will not show a name and have a blank icon. 
2. Non-interrupting abilities, especially those of hunters and shadow priests, will show as interrupting spells, even ones that cannot be interrupted. 

**To Reproduce**
1. Find an NPC that channels a spell such as rain of fire. 
2. Run an instance such as Scholomance with a hunter or shadow priest. NPCs will show their casts being interrupted while they continue to cast their spell.

**Expected behavior**
1. Spell icon and name properly displayed with channeled spells as it is with non-channeled spells.
2. Spells only being shown as interrupted when NPC is hit with an interrupting ability.

**Additional context**
I originally noticed the second issue while in Scholomance. Spells would consistently be shown as being interrupted by a shadow priest or a hunter, but the cast bar would usually pop back up after a moment and the NPC would continue casting. Even Gandling's arcane missiles, which are not interruptible, would show as being interrupted.
The first issue affects pretty much every channeled spell. I noticed it consistently while in Zul'Gurub, with the axe-throwers' whirlwind.

**Comment by Luxocracy** [comment]
Not sure if this is intentional or not by Blizzard, but it seems like you can't actually get a units channeling status. Even though they've gone ahead and added this natively for normal casting spells.

I believe channeling spells never worked correctly previously in NeatPlates in Classic as the old system only tracked normal spell casts. But I've implemented a basic version based on the old spell casting approximation, but I honestly don't know how helpful it will be in practice.

And because of this I've also added an option to hide channeled spellcasting bars so the addon will behave like it has previously.

The issue with Non-interrupting abilities showing as interrupting I honestly have no idea why that would happen, unless this is something that was prior to this week. In which case it might be some mismatched spell IDs. 

Other than that I currently have no way of actually testing this in SoD as I do not have a character of the appropriate level.

**Comment by Ainlaen** [comment]
I appreciate the quick response and all the work you've done with the addon. If I'm able to narrow down what's going on with the spell interrupts, I'll open a new issue. Thanks.
