### ISSUE TITLE
Transparency sliders reversing

### ISSUE THREAD

**Issue by blackmyin** [Luxocracy/NeatPlates#435]
**What version of the game you are experiencing the issue with:**
Season of Discovery

**Describe the bug**
When entering a transparency value in ANY color picker within options it gets reversed as soon as you hit okay. Example: entering 100% saves as 0% instead.

**To Reproduce**
Go to options for NeatPlates and select ANY color picker and drag the transparency slider in any direction and select "Okay".

**Expected behavior**
Entered transparency value should be the saved value.

**Additional context**
Unsure if this is related but using "Enable Pandemic Highlighting" under the "Aura Widget" and choosing "Glow" doesn't show the correct color chosen when glowing, glow always appears as standard white/yellowish.

Tested with all other addons disabled and NeatPlates v449.

**Comment by Luxocracy** [comment]
Colorpicker should be fixed in the latest version now. This was an issue retail had a while back and seems they updated it to match with retail now in Classic.

As for the "Glow" pandemic effect, sadly this effect cannot be colored. So I guess it's a bit incorrect to still be showing the colorbox when it's selected.

**Comment by blackmyin** [comment]
Confirmed working now!
