### ISSUE TITLE
Any update for 8.1?

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#46]
Any update for 8.1?
Thanks in advance.

**Comment by Diablolock** [comment]
I was wondering the same xD

**Comment by Luxocracy** [comment]
Did something break that I am unaware of in 8.1? Or are you just looking for a version bump so that it doesn't show as out of date?

Because I don't really have any feature updates planned until January due to holidays etc.

**Comment by Luxocracy** [comment]
I was going to post how it isn't allowed on curse due to the original addon being posted under an 'all rights reserved' kind of license. But it would seem that the licensing of the original has been changed to an 'MIT license, which as far as I am aware would allow this to get back into curse.

Will contact the mods on curse and see if it can be restored to curse.

**Comment by Diablolock** [comment]
Great news man! I hope we can get this awsome addon on curse asap! GL to us xD

**Comment by Luxocracy** [comment]
This has now properly been updated for 8.1, you can get it from [Curse](https://wow.curseforge.com/projects/neat-plates) or [GitHub](https://github.com/Luxocracy/NeatPlates/releases/tag/6.22).
