### ISSUE TITLE
New theme resquest

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#47]
Hey I´d like to ask for a new theme. Recently I´ve got this addon called SUI (https://www.wowinterface.com/downloads/info24007-SUI.html) and it has an amazing nameplate texture. Maybe we can get this into our TPC :)

Look for the texture folders in the .zip file on interface folder.

Thx in advance!

**Comment by Luxocracy** [comment]
If it's just the texture you're after I think you'd be better off just replacing one of the existing themes 'statusbar' texture than me guessing from a texture alone what it is that you want out of the theme.

**Comment by ja0b** [comment]
@Diablolock is something like this what you have in mind?

[TidyPlatesContinued_SUI.zip](https://github.com/Luxocracy/NeatPlates/files/2774981/TidyPlatesContinued_SUI.zip)

**Comment by Diablolock** [comment]
> 
> 
> @Diablolock is something like this what you have in mind?
> 
> [TidyPlatesContinued_SUI.zip](https://github.com/Luxocracy/NeatPlates/files/2774981/TidyPlatesContinued_SUI.zip)

Hi ja0b, first of all thx for that.

I extract the TidyPlatesContinued_SUI folder to my addon folder but when I go /hub the theme doesn't show in game. Any thing I'm missing?

**Comment by ja0b** [comment]
@Diablolock maybe is because you have the latest version, I know Luxo has been working a lot recently.
If that is the case just replace "TidyPlatesContinued" to "NeatPlates" in the folder name .lua and .toc files.

You can use another theme as an example (e.g NeatPlates_Neon ).
Let me know if that works. :)

**Comment by ja0b** [comment]
Actually, I just did it, I haven't tested but it should work, try with this. 👍 
[NeatPlates_SUI.zip](https://github.com/Luxocracy/NeatPlates/files/2775636/NeatPlates_SUI.zip)

**Comment by Diablolock** [comment]
I had a rollback to TidyPlatesContinued and the new theme shows on Theme list and it works (used the first versions of yours).

Now I updated to NeatPlates 6.22b-transition on curse and used your new version of the theme (NeatPlates_SUI) and it doesn't show on the theme list.

**Comment by Diablolock** [comment]
@ja0b I used the old version of TidyPlatesContinued with the old version of your TidyPlatesContinued_SUI - It works.

New version of NeatPlates with your new version of NeatPlates_SUI - It does not work.

Lmk if I get what your are telling me to do.

**Comment by ja0b** [comment]
Ok, but right now I don't access to the game to get a working version for NeatPlates so, using the old version of TidyPlatesContinued where the SUI theme works, could you please check the theme and tell me if that is what you wanted it? some feedback ?? maybe you want it more back?

Later on, I'll get a working version for NeatPlates for you to test but for now, it would be good to have some feedback. 👍

**Comment by Diablolock** [comment]
Gotcha!
Here a comparative between SUI and TPCTheme when I tested it out:
[https://imgur.com/XnyhEEH](url)

I would:
1) Keep the name position as it is on your theme (under the nameplate);
2) Make the border of the nameplate when targeted a bit thinner;
3) The red color of the nameplate on SUI original seems a bit brigther and more opaque at the same time. I don't know if it's possible to make it like that.

Other than that your work fits pretty well what I'm looking for :).

Thx!

**Comment by ja0b** [comment]
@Diablolock uhh... I think I understood you wrong then... I installed the addon and I didn't see any nameplates on, just the default blizzard one so I thought you were talking about implementing the kinda feel (black or at least that is what I saw) you are seeing something completely different.

What do I have to do to see the nameplates on using the SUI addon?  maybe I can implement the same thing here.

**Comment by Diablolock** [comment]
@ja0b No problem, it took me a while to figure out how to set SUI properly since the addon has different versions on curse and wowinterface.

I made a link with the folder you gotta paste into your wow folder to make it work properly:

https://1drv.ms/f/s!Anzcv9Lm7k6MjNpx3Tg4mToOBo9NYg

**Comment by Diablolock** [comment]
@ja0b Thinking it better, if you could bring the **exact same** nameplate from SUI to TPC it would fits my needs better! And maybe it´s also easier for you. ty!

**Comment by Luxocracy** [comment]
Just to save you some potential head scratching later on, the 'Debuff Widget' is anchored differently in Neat Plates compared to how it was in TPC. It's not a massive change, but is likely to cause some issues if you are basing it of TPC theme files.

**Comment by ja0b** [comment]
@Diablolock yesterday I finally had a look at this and found out that you don't require the SUI addon to get the plates working as you want the only thing you need put this in place:

Interface/
└── TargetingFrame/
         ├── UI-RaidTargetingIcons.blp
         ├── UI-StatusBar.blp
         └── UI-TargetingFrame-BarFill.blp

(you can even paste all the graphics you sent me for this folder and you will see the dark theme across wow)

These plates are the default blizzard nameplates with a REALLY minor enhancement, for some reason, I cannot reuse the graphics... I tried .blp & .tga none of them worked, all I got was a green box instead of the right image.

I was trying to prepare this for you only as IMO I don't see any value on this theme as "Simple" already does almost the same thing (even better).

@Luxocracy your call to close/archive this ticket, unless you see any value of having a "Modern Blizzard Plates" theme but it would be another one to mantain.

**Comment by Diablolock** [comment]
Ok @ja0b , thx for working on this!

@Luxocracy feel free to close this.
