### ISSUE TITLE
Neat Plates Installing TPC

### ISSUE THREAD

**Issue by ja0b** [Luxocracy/NeatPlates#51]
Hi @Luxocracy,
Just installed a fresh version on Neat Plates from the twitch client and the folders are called like before TPC.

**Comment by Luxocracy** [comment]
This is because I still haven't released the upcoming 6.22 version, which is the first version to actually use the Neat Plates moniker.

I wanted to make sure the name change was acceptable with the mods on Curse and to do some prep before actually releasing 6.22. And once I re-added the webhook between Curse and GitHub in preparation, it triggered a push of all the old TPC releases from GitHub to Curse making it seem like it is updated, but it is still just the latest TPC release.

I've got a few more things I want to make sure are working properly, as well as track down an issue I stumbled upon today where profiles randomly wouldn't repopulate properly.

As soon as that's taken care of I'll make a release and it should update properly through the Twitch client.
