### ISSUE TITLE
Hey Lux

### ISSUE THREAD

**Issue by Apoxiosis** [Luxocracy/NeatPlates#53]
Noticed you changed the project and re-added to curse. I updated with the beta version 6.22-beta-Transition

I logged in and copied my settings over from TPC, but when i nter combat the settings displayed arent matching what I have selected.

My neatplates settings seems to using the "general profile" instead of my character specific spec profiles

also, s a small suggestion, on the sidebar where it lists each individual characters settings, that could get way out of hand really quickly, showing 4 profiles for each character every time you log in. i suggest some way to consolidate

**Comment by Luxocracy** [comment]
The move to global profiles was made so that you wouldn't need 4 profiles per character. If you do actually end up using 4 profiles per character, I would start to question how different each of those profiles actually are.
This said I'm not quite happy with how it is now, it was mainly done because it was a lot simpler to use the already existing way of displaying profiles.

Now as for your profiles not loading, did you remember to actually select the correct profile for each spec in the main settings?

**Comment by Apoxiosis** [comment]
> Now as for your profiles not loading, did you remember to actually select the correct profile for each spec in the main settings?

I kinda elaborated on that mentioning NP is using my general profile. 

I originally went in and changed all my settings on my dps profile, then when i entered combat is when i noticed it was using settings from general instead of my spec profile.

I personally prefer having a global profile. about the only difference I need between specs is a different color scheme for threat when Im tanking.

That said though, I just wanted to make sure you was tracking it. I dunno how exactly you wanted it to work.

I still suggest a way to consolidate profiles though. Currently its showing about 8 or 9 profiles, 4 for each of my characters ive logged on since instealling NP + the global.

**Comment by Luxocracy** [comment]
I really feel like the issues you are having is a configuration issue on your end.
Because you are saying you only use 1 or 2 profiles, yet, you won't delete the unused ones that are causing clutter?

From what you're saying it seems like you've misunderstood how the profiles work.
All the profiles are global profiles, you need to set which profile is used for which spec. This is located in the main settings, not the profile specific settings. Everything you're saying makes it seem like these have all been left on the default profile

**Comment by Apoxiosis** [comment]
I see how it works now, just a minor difference from how it worked before when each spec specific profile activated when you changed specs.
