### ISSUE TITLE
Feature request: character specific setting for purgeable buff behavior

### ISSUE THREAD

**Issue by hollo6** [Luxocracy/NeatPlates#57]
Now with the amazing global profile system, I'd like to set up a universal profile I can use across all my toons so for example, if I encounter a new buff/debuff I want to put on the aura filter list, I'd only have to do it once for that one profile and happily use it on every one of them. The one thing I can't make global is the purgeable buffs because I want them shown in a way that they only glow for characters that can actually dispel them. If you could come up with some solution for this, I'd be most grateful!

**Comment by Luxocracy** [comment]
I am a little bit against this suggestion because I would like to stay away from manually defining things for certain classes as they may change over time.
But if I can find some other way it is something that I would consider doing.

**Comment by hollo6** [comment]
I know that you don't want to hardcode class specific settings, that's why I was suggesting an option we can configure for ourselves on a per character basis.

**Comment by Luxocracy** [comment]
So basically this would be a 'profile' within a profile?
The only way I can think of implementing this in a way that I'd be okay with is to have 'Advanced Profiles'.

Where these 'Advanced Profiles' would use the settings from another profile, and then have check marks next to each setting which would make them override the base profiles settings.
But that would be a pretty huge time investment to make that work for something so niche.

**Comment by hollo6** [comment]
The new global aura filter is great! Would you please add the same for emphasized auras? Thanks :)

**Comment by Luxocracy** [comment]
I added the same thing for Emphasizes auras. I have only done some brief testing on both of these so there might be some issues with how it prioritizes auras when it has auras from both the 'global' and 'profile' sections. But I don't think it will cause any issues, if it does I will look into it at that point.

**Comment by hollo6** [comment]
Looking good so far! Although I know this is not strictly related to the original topic, emphasized auras' behavior is a little strange. I haven't done much testing but:
- I have to list the auras in the "normal" list in addition to the emphasized list in order to see them.
- When there are more than 1 emphasized auras on a unit, only one of them will be shown as emphasized.
I don't know if it should work this way, just feels weird.

**Comment by Luxocracy** [comment]
The emphasized aura is limited to show only 1 aura at the moment, I feel like it would lose it's purpose if it were to show all the auras at once since you might as well just scale up the normal auras at that point.
I was considering adding an option to increase the amount displayed to 2 or 3 but any more than that and I feel like it would lose it's meaning.

As for having to list the auras in the "normal" list first, this isn't intended. This could be because of an oversight on my part because I usually have "track my debuffs" checked. But I'm fairly sure I had that disabled when I was adding this feature so it might be something else when you have certain options enabled. I'll look into.

**Comment by hollo6** [comment]
Thanks, I will test it tonight. In the meantime:
I think displaying 2 or 3 emphasized auras would be enough (for example, I want to use this feature to track CCs, and it would be nice to see if there are more on a mob so it won't get out of CCwhen one of them fades).
Also I just discovered that global aura filters are not global but per character. Could you please fix this too?

**Comment by Luxocracy** [comment]
You are absolutely right about the global aura filters not being global...
I'm not sure how I overlooked this since I recently fixed a mistake similar to this that I had made regarding the "Default" profile not being assigned across characters.

**Comment by hollo6** [comment]
I think you should just store all the settings globally. It would be so much easier to manage, for users as well. For example, I'm using multiple computers and then I'd just have to copy the per-account NP settings files.

**Comment by Luxocracy** [comment]
There are still a few settings that are way easier to deal with if they are defined per-character both from a programming perspective as well as user perspective. Because I believe the per-character settings automatically follow you if you have a character transfer or name change. While if those were defined globally they would be lost because the assigned character no longer exists.

Even if they didn't automatically follow, the solution would be a simple copy-paste. While if they were stored globally it would require editing the files.

**Comment by hollo6** [comment]
Understood, it was just an idea. Also I have lost ALL my aura filters (from global list and all profiles) with version 6.22.3b, so I think it would be best to cancel that release.

**Comment by Luxocracy** [comment]
Something must have happened on your end, because that release, and the one after, only deals with minor bug fixes such as rare lua errors and nameplate scaling.

**Comment by hollo6** [comment]
Maybe it was an earlier version, I went there from 6.22.2
