### ISSUE TITLE
Target Nameplate Scale

### ISSUE THREAD

**Issue by Rhess86** [Luxocracy/NeatPlates#65]
Hi, with this new update i noticed some changes on my name places even tough i didnt change anything, 
All my nameplates became smaller, which i had to increase the normal scale, but the most annoying is the target nameplate becoming A LOT bigger than the others. I've tried to change all the scales on the options but nothing seems to work. Any help? Thanks.

**Comment by Luxocracy** [comment]
This is due to a recent change where the nameplates will adhere to the scaling of certain blizzard functions for nameplates, which allows for such things as nameplate scaling based on distance.

I usually "Spotlight" my target which makes it bigger, so I didn't notice the change immediately. The next release will have an option, disabled by default, that will enable and disable this feature.

Until then you can use this command to make your nameplates behave like before, as this seems to be the culprit causing it.
`/run SetCVar("nameplateMinScale", 1)`

**Comment by Rhess86** [comment]
I also use spotlight, but very little, like my normal is 150% and my spotlight is 160%, but with the update i've had to set the normal to 180%(to be like before) and the spotlight is like 250%, but moving the sliders wont change the size, its frozen super big. I'll try the command later since i went back to the previous version. Thanks for the quick reply.

**Comment by Luxocracy** [comment]
In the latest version(6.22.4), nameplate scaling should now behave like it used to unless you enable "Blizzard Scaling" under options that is.
