### ISSUE TITLE
Nameplate settings reseting after a reload/relog

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#77]
After new patch (8.1.5) all the settings keep reseting after a reload/relog.

Have any of you noticed this?

/e
The main setting I've experienced this is Overlapping/Stacking Nameplates.

**Comment by Luxocracy** [comment]
From looking into it, it seems like any CVars related to nameplates are being reset when you reload/relog.

I believe this is an issue on blizzards end and hopefully they will fix it soon. But until then I will most likely add a "Enforce CVars" type setting so that the addon sets CVars when loaded.
If you want a fix right now, I would recommend checking out [AdvancedInterfaceOptions](https://www.curseforge.com/wow/addons/advancedinterfaceoptions) as this lets you set any CVars and already has a "Enforce CVars" setting to deal with issues like this.

**Comment by Diablolock** [comment]
Ty Lux! Both WA and AIO enforce cvars works good as a temporary fix.

I also found this thread reporting multiple users with same bug:

https://us.forums.blizzard.com/en/wow/t/nameplate-cvars-are-resetting-on-reload-relog/123098/16

**Comment by yishuangfrank** [comment]
Blizzard fixed it already.
