### ISSUE TITLE
An issue for Souls in Mythic+ Dungeon

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#79]
When a **_Soul_** dies, its health bar restores full and disappears immediately.
NeatPlates_Quatre，v6.22.8b

**Comment by Luxocracy** [comment]
It sounds like what you are describing is that the unit gets to 0 health, and instead of the health bar disappearing like it normally would, it displays as the unit having full health and then finally disappears. But I'm not quite sure if this is what's happening as your description of the issue is rather basic.

I've not seen anything close to this issue while playing myself but from the sound of it, I'm not sure what can actually be done. When a nameplate should exist or not is generally decided by blizzard and an addon doesn't really have much say in the matter.

As for the health, I can only assume that the function provided by blizzard to get the health of a unit is returning an incorrect value when it dies. Because the addons health update function should default to 0 if it cannot get one from the unit.

**Comment by ja0b** [comment]
@Luxocracy I think what you described above is what it's happening, I just saw that behaviour while doing M+, playing as Tank v6.22.8b.

**Comment by yishuangfrank** [comment]
@Luxocracy ,your description is right.
As you said, maybe it's Blizzard's fault, just like the reset Cvars.
