### ISSUE TITLE
Default plates showing underneath addon plates

### ISSUE THREAD

**Issue by Twinbladezz** [Luxocracy/NeatPlates#80]
Hello,

I am still experiencing an issue with the default plates showing underneath the addon plates. I know that a fix had been done a couple of days ago regarding this issue and I have the most recent file downloaded. Just confused why its not working.. 

Here is an attached image of what I'm seeing in game..
![Nameplates](https://user-images.githubusercontent.com/48658155/54497684-1ab75580-48d4-11e9-822d-f38ccbfe2036.png)

**Comment by Luxocracy** [comment]
Is this a constant issue you are having?
Because that is what it sounds like to me when you are talking about it, and the fix was for a very rare bug that was happening. If you are constantly seeing multiple nameplates, I would look into what other addons might be affecting nameplates.

If not, I would need some more info on how to re-produce this issue as obviously something else is causing this issue to happen than I originally thought.
