### ISSUE TITLE
Truesight icon being obscured by nameplates

### ISSUE THREAD

**Issue by CaffeineFueled** [Luxocracy/NeatPlates#81]
Love the addon.  Thank you very much for your hard work.

Something newish that I'm having an issue with is that the truesight icon that shows above mobs who can see through stealth/invisibility has been getting obscured by NeatPlates.  I don't remember this being an issue, but I suddenly find myself face pulling tons of stuff.

I don't remember exactly when this started happening I've been ignoring it for so long now, but last night I caused us to wipe in M+ because of it so I figured I'd ask around.

Has anyone else experienced this?  Am I doing something wrong?  Has something really changed?

I suppose I should mention this is with the stock Neon theme.

Thanks!

**Comment by Luxocracy** [comment]
This is how it appears for me when I went and checked and compared it to the default nameplates.
![](https://imgur.com/WIkszEl.jpg) ![](https://imgur.com/bpPhA8c.jpg)

The addon plates are definitively a tad bit lower, but not enough to cause issues in my opinion, and while I might be able to bump them up a bit. This is something that is very likely to cause targeting issues as they are currently right in the center of the "hitbox" for targeting. And the positioning of that is something out of my control sadly.

**Comment by CaffeineFueled** [comment]
Hmm.  That is very different than how mine look.  Let me see if I can find a truesight mob real quick.

**Comment by Luxocracy** [comment]
What you could do to ease this issue is to look under the "Funky Stuff" category for _Vertical Position of Artwork_, and increase that slightly.
Secondly, since you are moving the artwork up, you will also have to increase the height of said "hitbox" to avoid any targeting issues. This can be done in the **Main** settings, and is called _Clickable Height_.

This would be about the same as what I could do to mitigate the issue.

**Comment by Luxocracy** [comment]
Another thing might be that this is just different depending on the mob in which case, once again, I'm not sure I could do anything about it.

**Comment by CaffeineFueled** [comment]
![image](https://user-images.githubusercontent.com/6114721/54840625-c9c4aa00-4ca3-11e9-916d-bd18333acf6f.png)

**Comment by CaffeineFueled** [comment]
Moving artwork up to 100% seems to have helped.  I'll run with this for a bit see if it works out.

Thanks!

![image](https://user-images.githubusercontent.com/6114721/54840915-72730980-4ca4-11e9-8956-5fc4c990a102.png)

**Comment by Luxocracy** [comment]
Wow, that is pretty bad. And I went to look at the Overseer specifically to compare and my nameplates cover it completely as well on that mob.

So I guess it's something blizz needs to define per mob so that it offsets properly. And perhaps they forgot? Because it wouldn't be the first time something like this was forgotten.

**Comment by CaffeineFueled** [comment]
Maybe it's a Kul Tiran thing?  The mob I aggroed last night was Kul Tiran as well.

**Comment by Luxocracy** [comment]
I'll look into if there's any way to possibly detect if a unit has stealth detection so I could add an icon to the actual nameplate as an indication that they have stealth detection.
But I doubt there is as I kinda remember looking in the past and not finding any way.
