### ISSUE TITLE
Neatplate Error

### ISSUE THREAD

**Issue by LasVenturas92** [Luxocracy/NeatPlates#96]
Ive got this since like a week a few minutes ingame and i get

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:707: attempt to index field 'focus' (a nil value)
Time: Sun Jun 16 15:48:40 2019
Count: 3430
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:707: attempt to index field 'focus' (a nil value)
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:707: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:703>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:340: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:325>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:457: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:447>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:166: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:143>

Locals: current = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'focus' (a nil value)"
unit = <table> {
 guid = "Creature-0-3113-1643-12031-131387-0003063987"
 isMouseover = false
 class = ""
 rawName = "Coppertail Fox"
 threatSituation = "LOW"
 red = 0.999998
 levelcolorRed = 1
 unitid = "nameplate3"
 isMini = false
 pvpname = "Coppertail Fox"
 levelcolorBlue = 0
 isInCombat = false
 isBoss = false
 isFocus = false
 healthmax = 66221
 isTarget = false
 levelcolorGreen = 0.820000
 absorbmax = 0
 isTapped = false
 absorb = 0
 blue = 0
 style = "Default"
 isMarked = false
 level = 120
 type = "NPC"
 isCasting = false
 reaction = "NEUTRAL"
 green = 0.999998
 health = 66221
 threatValue = 0
 isDangerous = false
 name = "Coppertail Fox"
}
style = <table> {
 customtext = <table> {
 }
 highlight = <table> {
 }
 threatcolor = <table> {
 }
 spellicon = <table> {
 }
 spelltext = <table> {
 }
 target = <table> {
 }
 level = <table> {
 }
 castnostop = <table> {
 }
 healthbar = <table> {
 }
 healthborder = <table> {
 }
 skullicon = <table> {
 }
 threatborder = <table> {
 }
 mouseover = <table> {
 }
 focus = <table> {
 }
 castbar = <table> {
 }
 name = <table> {
 }
 castborder = <table> {
 }
 hitbox = <table> {
 }
 eliteicon = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 raidicon = <table> {
 }
}
visual = <table> {
 highlight = <unnamed> {
 }
 customtext = <unnamed> {
 }
 healthbar = <unnamed> {
 }
 healthborder = <unnamed> {
 }
 castborder = <unnamed> {
 }
 threatborder = <unnamed> {
 }
 skullicon = <unnamed> {
 }
 castnostop = <unnamed> {
 }
 spellicon = <unnamed> {
 }
 eliteicon = <unnamed> {
 }
 name = <unnamed> {
 }
 spelltext = <unnamed> {
 }
 target = <unnamed> {
 }
 level = <unnamed> {
 }
 castbar = <unnamed> {
 }
 raidicon = <unnamed> {
 }
}

And yes iam on the latest version and i tried reinstall and all

**Comment by Luxocracy** [comment]
This seems to be the same issue as #95, and as I mentioned there this error doesn't really make sense when looking at the code. Because some of the texture frames seem to be missing, but only the new ones added in 6.23. The ones that existed previously seem to still be there and if it just didn't create the new ones the error should occur at a different point in the code.

My best guess right now is that this might be something related to caching.
I would try clearing your cache by removing the _Cache_ folder located in your retail WoW folder `World of Warcraft\_retail_` and see if that helps.

**Comment by LasVenturas92** [comment]
Clearing my cache didnt work

**Comment by Luxocracy** [comment]
Does this still happen if Neatplates is the only active addon? And if it does could you attach your _NeatPlatesHub.lua_ file located here: `World of Warcraft\_retail_\WTF\Account\ACCOUNTID\SavedVariables` so I can easily rule out if this is caused by an interaction of certain settings, as I'm having a really hard time getting this error to occur on my end.

**Comment by LasVenturas92** [comment]
Ok i guess i figured it out, somehow for some reason i had Tidyplates in the list and it was running, after i removed it it stopped giving errors

**Comment by Luxocracy** [comment]
Glad you got it fixed, and that explains why the old frames where there but not the new ones.
