### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#98]
Some icons block the Left Arrow：
![TIM截图20190712234403](https://user-images.githubusercontent.com/44251440/61174131-baf56080-a5ce-11e9-8d70-5069faabc29c.png)
![TIM截图20190713090638](https://user-images.githubusercontent.com/44251440/61174133-bcbf2400-a5ce-11e9-9f5f-18c63c365287.png)

**Comment by Luxocracy** [comment]
I'm assuming that the second image is there to show how it should be? Because I can definitely fix it so that the arrows appear on top.

Any other solution would probably require moving most icons around to prevent the blocking from happening. Which I really would want to avoid as it would change the look of the themes too much.

**Comment by yishuangfrank** [comment]
There are too may icons on the left side of the nameplate. How about this?
Add an “Arrow(Right Side)” option，only show the arrow on the right side of the nameplate.

BTW，Can we change the size of the arrow？

**Comment by Luxocracy** [comment]
Another option to just display the arrow on the right is a pretty simple solution. And no, you can't currently change the size of it, but that should be quite easy to add as well.
